// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/micro/services/m3o/api/proto/m3o.proto

package go_micro_api_m3o

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string           `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string           `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string           `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	ProfilePictureUrl    string           `protobuf:"bytes,5,opt,name=profile_picture_url,json=profilePictureUrl,proto3" json:"profile_picture_url,omitempty"`
	PaymentMethods       []*PaymentMethod `protobuf:"bytes,6,rep,name=payment_methods,json=paymentMethods,proto3" json:"payment_methods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetProfilePictureUrl() string {
	if m != nil {
		return m.ProfilePictureUrl
	}
	return ""
}

func (m *User) GetPaymentMethods() []*PaymentMethod {
	if m != nil {
		return m.PaymentMethods
	}
	return nil
}

type ReadAccountRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAccountRequest) Reset()         { *m = ReadAccountRequest{} }
func (m *ReadAccountRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAccountRequest) ProtoMessage()    {}
func (*ReadAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{1}
}

func (m *ReadAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAccountRequest.Unmarshal(m, b)
}
func (m *ReadAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAccountRequest.Marshal(b, m, deterministic)
}
func (m *ReadAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAccountRequest.Merge(m, src)
}
func (m *ReadAccountRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAccountRequest.Size(m)
}
func (m *ReadAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAccountRequest proto.InternalMessageInfo

type ReadAccountResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAccountResponse) Reset()         { *m = ReadAccountResponse{} }
func (m *ReadAccountResponse) String() string { return proto.CompactTextString(m) }
func (*ReadAccountResponse) ProtoMessage()    {}
func (*ReadAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{2}
}

func (m *ReadAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAccountResponse.Unmarshal(m, b)
}
func (m *ReadAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAccountResponse.Marshal(b, m, deterministic)
}
func (m *ReadAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAccountResponse.Merge(m, src)
}
func (m *ReadAccountResponse) XXX_Size() int {
	return xxx_messageInfo_ReadAccountResponse.Size(m)
}
func (m *ReadAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAccountResponse proto.InternalMessageInfo

func (m *ReadAccountResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type Project struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string         `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Repository           string         `protobuf:"bytes,4,opt,name=repository,proto3" json:"repository,omitempty"`
	Environments         []*Environment `protobuf:"bytes,5,rep,name=environments,proto3" json:"environments,omitempty"`
	Members              []*Member      `protobuf:"bytes,6,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{3}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Project) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *Project) GetEnvironments() []*Environment {
	if m != nil {
		return m.Environments
	}
	return nil
}

func (m *Project) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

type Member struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Role                 string   `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{4}
}

func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (m *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(m, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Member) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Member) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Member) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Member) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type CreateProjectRequest struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	GithubToken          string   `protobuf:"bytes,2,opt,name=github_token,json=githubToken,proto3" json:"github_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectRequest) Reset()         { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()    {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{5}
}

func (m *CreateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectRequest.Unmarshal(m, b)
}
func (m *CreateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectRequest.Marshal(b, m, deterministic)
}
func (m *CreateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectRequest.Merge(m, src)
}
func (m *CreateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProjectRequest.Size(m)
}
func (m *CreateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectRequest proto.InternalMessageInfo

func (m *CreateProjectRequest) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *CreateProjectRequest) GetGithubToken() string {
	if m != nil {
		return m.GithubToken
	}
	return ""
}

type CreateProjectResponse struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret         string   `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectResponse) Reset()         { *m = CreateProjectResponse{} }
func (m *CreateProjectResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProjectResponse) ProtoMessage()    {}
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{6}
}

func (m *CreateProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectResponse.Unmarshal(m, b)
}
func (m *CreateProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectResponse.Marshal(b, m, deterministic)
}
func (m *CreateProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectResponse.Merge(m, src)
}
func (m *CreateProjectResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProjectResponse.Size(m)
}
func (m *CreateProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectResponse proto.InternalMessageInfo

func (m *CreateProjectResponse) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *CreateProjectResponse) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *CreateProjectResponse) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

type UpdateProjectRequest struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProjectRequest) Reset()         { *m = UpdateProjectRequest{} }
func (m *UpdateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProjectRequest) ProtoMessage()    {}
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{7}
}

func (m *UpdateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProjectRequest.Unmarshal(m, b)
}
func (m *UpdateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProjectRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProjectRequest.Merge(m, src)
}
func (m *UpdateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProjectRequest.Size(m)
}
func (m *UpdateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProjectRequest proto.InternalMessageInfo

func (m *UpdateProjectRequest) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type UpdateProjectResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProjectResponse) Reset()         { *m = UpdateProjectResponse{} }
func (m *UpdateProjectResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProjectResponse) ProtoMessage()    {}
func (*UpdateProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{8}
}

func (m *UpdateProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProjectResponse.Unmarshal(m, b)
}
func (m *UpdateProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProjectResponse.Marshal(b, m, deterministic)
}
func (m *UpdateProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProjectResponse.Merge(m, src)
}
func (m *UpdateProjectResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProjectResponse.Size(m)
}
func (m *UpdateProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProjectResponse proto.InternalMessageInfo

type ListProjectsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProjectsRequest) Reset()         { *m = ListProjectsRequest{} }
func (m *ListProjectsRequest) String() string { return proto.CompactTextString(m) }
func (*ListProjectsRequest) ProtoMessage()    {}
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{9}
}

func (m *ListProjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectsRequest.Unmarshal(m, b)
}
func (m *ListProjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectsRequest.Marshal(b, m, deterministic)
}
func (m *ListProjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectsRequest.Merge(m, src)
}
func (m *ListProjectsRequest) XXX_Size() int {
	return xxx_messageInfo_ListProjectsRequest.Size(m)
}
func (m *ListProjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectsRequest proto.InternalMessageInfo

type ListProjectsResponse struct {
	Projects             []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListProjectsResponse) Reset()         { *m = ListProjectsResponse{} }
func (m *ListProjectsResponse) String() string { return proto.CompactTextString(m) }
func (*ListProjectsResponse) ProtoMessage()    {}
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{10}
}

func (m *ListProjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectsResponse.Unmarshal(m, b)
}
func (m *ListProjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectsResponse.Marshal(b, m, deterministic)
}
func (m *ListProjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectsResponse.Merge(m, src)
}
func (m *ListProjectsResponse) XXX_Size() int {
	return xxx_messageInfo_ListProjectsResponse.Size(m)
}
func (m *ListProjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectsResponse proto.InternalMessageInfo

func (m *ListProjectsResponse) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

type ValidateGithubTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateGithubTokenRequest) Reset()         { *m = ValidateGithubTokenRequest{} }
func (m *ValidateGithubTokenRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateGithubTokenRequest) ProtoMessage()    {}
func (*ValidateGithubTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{11}
}

func (m *ValidateGithubTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateGithubTokenRequest.Unmarshal(m, b)
}
func (m *ValidateGithubTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateGithubTokenRequest.Marshal(b, m, deterministic)
}
func (m *ValidateGithubTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateGithubTokenRequest.Merge(m, src)
}
func (m *ValidateGithubTokenRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateGithubTokenRequest.Size(m)
}
func (m *ValidateGithubTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateGithubTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateGithubTokenRequest proto.InternalMessageInfo

func (m *ValidateGithubTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ValidateGithubTokenResponse struct {
	Repos                []*Repository `protobuf:"bytes,1,rep,name=repos,proto3" json:"repos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ValidateGithubTokenResponse) Reset()         { *m = ValidateGithubTokenResponse{} }
func (m *ValidateGithubTokenResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateGithubTokenResponse) ProtoMessage()    {}
func (*ValidateGithubTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{12}
}

func (m *ValidateGithubTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateGithubTokenResponse.Unmarshal(m, b)
}
func (m *ValidateGithubTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateGithubTokenResponse.Marshal(b, m, deterministic)
}
func (m *ValidateGithubTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateGithubTokenResponse.Merge(m, src)
}
func (m *ValidateGithubTokenResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateGithubTokenResponse.Size(m)
}
func (m *ValidateGithubTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateGithubTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateGithubTokenResponse proto.InternalMessageInfo

func (m *ValidateGithubTokenResponse) GetRepos() []*Repository {
	if m != nil {
		return m.Repos
	}
	return nil
}

type WebhookAPIKeyRequest struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebhookAPIKeyRequest) Reset()         { *m = WebhookAPIKeyRequest{} }
func (m *WebhookAPIKeyRequest) String() string { return proto.CompactTextString(m) }
func (*WebhookAPIKeyRequest) ProtoMessage()    {}
func (*WebhookAPIKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{13}
}

func (m *WebhookAPIKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebhookAPIKeyRequest.Unmarshal(m, b)
}
func (m *WebhookAPIKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebhookAPIKeyRequest.Marshal(b, m, deterministic)
}
func (m *WebhookAPIKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebhookAPIKeyRequest.Merge(m, src)
}
func (m *WebhookAPIKeyRequest) XXX_Size() int {
	return xxx_messageInfo_WebhookAPIKeyRequest.Size(m)
}
func (m *WebhookAPIKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WebhookAPIKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WebhookAPIKeyRequest proto.InternalMessageInfo

func (m *WebhookAPIKeyRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type WebhookAPIKeyResponse struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret         string   `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebhookAPIKeyResponse) Reset()         { *m = WebhookAPIKeyResponse{} }
func (m *WebhookAPIKeyResponse) String() string { return proto.CompactTextString(m) }
func (*WebhookAPIKeyResponse) ProtoMessage()    {}
func (*WebhookAPIKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{14}
}

func (m *WebhookAPIKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebhookAPIKeyResponse.Unmarshal(m, b)
}
func (m *WebhookAPIKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebhookAPIKeyResponse.Marshal(b, m, deterministic)
}
func (m *WebhookAPIKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebhookAPIKeyResponse.Merge(m, src)
}
func (m *WebhookAPIKeyResponse) XXX_Size() int {
	return xxx_messageInfo_WebhookAPIKeyResponse.Size(m)
}
func (m *WebhookAPIKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WebhookAPIKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WebhookAPIKeyResponse proto.InternalMessageInfo

func (m *WebhookAPIKeyResponse) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *WebhookAPIKeyResponse) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

type Repository struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Private              bool     `protobuf:"varint,2,opt,name=private,proto3" json:"private,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Repository) Reset()         { *m = Repository{} }
func (m *Repository) String() string { return proto.CompactTextString(m) }
func (*Repository) ProtoMessage()    {}
func (*Repository) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{15}
}

func (m *Repository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repository.Unmarshal(m, b)
}
func (m *Repository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repository.Marshal(b, m, deterministic)
}
func (m *Repository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repository.Merge(m, src)
}
func (m *Repository) XXX_Size() int {
	return xxx_messageInfo_Repository.Size(m)
}
func (m *Repository) XXX_DiscardUnknown() {
	xxx_messageInfo_Repository.DiscardUnknown(m)
}

var xxx_messageInfo_Repository proto.InternalMessageInfo

func (m *Repository) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Repository) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

type PaymentMethod struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	CardBrand            string   `protobuf:"bytes,3,opt,name=card_brand,json=cardBrand,proto3" json:"card_brand,omitempty"`
	CardExpMonth         string   `protobuf:"bytes,4,opt,name=card_exp_month,json=cardExpMonth,proto3" json:"card_exp_month,omitempty"`
	CardExpYear          string   `protobuf:"bytes,5,opt,name=card_exp_year,json=cardExpYear,proto3" json:"card_exp_year,omitempty"`
	CardLast_4           string   `protobuf:"bytes,6,opt,name=card_last_4,json=cardLast4,proto3" json:"card_last_4,omitempty"`
	Default              bool     `protobuf:"varint,7,opt,name=default,proto3" json:"default,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentMethod) Reset()         { *m = PaymentMethod{} }
func (m *PaymentMethod) String() string { return proto.CompactTextString(m) }
func (*PaymentMethod) ProtoMessage()    {}
func (*PaymentMethod) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{16}
}

func (m *PaymentMethod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethod.Unmarshal(m, b)
}
func (m *PaymentMethod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethod.Marshal(b, m, deterministic)
}
func (m *PaymentMethod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethod.Merge(m, src)
}
func (m *PaymentMethod) XXX_Size() int {
	return xxx_messageInfo_PaymentMethod.Size(m)
}
func (m *PaymentMethod) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethod.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethod proto.InternalMessageInfo

func (m *PaymentMethod) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PaymentMethod) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *PaymentMethod) GetCardBrand() string {
	if m != nil {
		return m.CardBrand
	}
	return ""
}

func (m *PaymentMethod) GetCardExpMonth() string {
	if m != nil {
		return m.CardExpMonth
	}
	return ""
}

func (m *PaymentMethod) GetCardExpYear() string {
	if m != nil {
		return m.CardExpYear
	}
	return ""
}

func (m *PaymentMethod) GetCardLast_4() string {
	if m != nil {
		return m.CardLast_4
	}
	return ""
}

func (m *PaymentMethod) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

type CreatePaymentMethodRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePaymentMethodRequest) Reset()         { *m = CreatePaymentMethodRequest{} }
func (m *CreatePaymentMethodRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePaymentMethodRequest) ProtoMessage()    {}
func (*CreatePaymentMethodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{17}
}

func (m *CreatePaymentMethodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePaymentMethodRequest.Unmarshal(m, b)
}
func (m *CreatePaymentMethodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePaymentMethodRequest.Marshal(b, m, deterministic)
}
func (m *CreatePaymentMethodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePaymentMethodRequest.Merge(m, src)
}
func (m *CreatePaymentMethodRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePaymentMethodRequest.Size(m)
}
func (m *CreatePaymentMethodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePaymentMethodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePaymentMethodRequest proto.InternalMessageInfo

func (m *CreatePaymentMethodRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreatePaymentMethodResponse struct {
	PaymentMethod        *PaymentMethod `protobuf:"bytes,1,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreatePaymentMethodResponse) Reset()         { *m = CreatePaymentMethodResponse{} }
func (m *CreatePaymentMethodResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePaymentMethodResponse) ProtoMessage()    {}
func (*CreatePaymentMethodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{18}
}

func (m *CreatePaymentMethodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePaymentMethodResponse.Unmarshal(m, b)
}
func (m *CreatePaymentMethodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePaymentMethodResponse.Marshal(b, m, deterministic)
}
func (m *CreatePaymentMethodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePaymentMethodResponse.Merge(m, src)
}
func (m *CreatePaymentMethodResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePaymentMethodResponse.Size(m)
}
func (m *CreatePaymentMethodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePaymentMethodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePaymentMethodResponse proto.InternalMessageInfo

func (m *CreatePaymentMethodResponse) GetPaymentMethod() *PaymentMethod {
	if m != nil {
		return m.PaymentMethod
	}
	return nil
}

type DeletePaymentMethodRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePaymentMethodRequest) Reset()         { *m = DeletePaymentMethodRequest{} }
func (m *DeletePaymentMethodRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePaymentMethodRequest) ProtoMessage()    {}
func (*DeletePaymentMethodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{19}
}

func (m *DeletePaymentMethodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePaymentMethodRequest.Unmarshal(m, b)
}
func (m *DeletePaymentMethodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePaymentMethodRequest.Marshal(b, m, deterministic)
}
func (m *DeletePaymentMethodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePaymentMethodRequest.Merge(m, src)
}
func (m *DeletePaymentMethodRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePaymentMethodRequest.Size(m)
}
func (m *DeletePaymentMethodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePaymentMethodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePaymentMethodRequest proto.InternalMessageInfo

func (m *DeletePaymentMethodRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeletePaymentMethodResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePaymentMethodResponse) Reset()         { *m = DeletePaymentMethodResponse{} }
func (m *DeletePaymentMethodResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePaymentMethodResponse) ProtoMessage()    {}
func (*DeletePaymentMethodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{20}
}

func (m *DeletePaymentMethodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePaymentMethodResponse.Unmarshal(m, b)
}
func (m *DeletePaymentMethodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePaymentMethodResponse.Marshal(b, m, deterministic)
}
func (m *DeletePaymentMethodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePaymentMethodResponse.Merge(m, src)
}
func (m *DeletePaymentMethodResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePaymentMethodResponse.Size(m)
}
func (m *DeletePaymentMethodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePaymentMethodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePaymentMethodResponse proto.InternalMessageInfo

type DefaultPaymentMethodRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefaultPaymentMethodRequest) Reset()         { *m = DefaultPaymentMethodRequest{} }
func (m *DefaultPaymentMethodRequest) String() string { return proto.CompactTextString(m) }
func (*DefaultPaymentMethodRequest) ProtoMessage()    {}
func (*DefaultPaymentMethodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{21}
}

func (m *DefaultPaymentMethodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultPaymentMethodRequest.Unmarshal(m, b)
}
func (m *DefaultPaymentMethodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultPaymentMethodRequest.Marshal(b, m, deterministic)
}
func (m *DefaultPaymentMethodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultPaymentMethodRequest.Merge(m, src)
}
func (m *DefaultPaymentMethodRequest) XXX_Size() int {
	return xxx_messageInfo_DefaultPaymentMethodRequest.Size(m)
}
func (m *DefaultPaymentMethodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultPaymentMethodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultPaymentMethodRequest proto.InternalMessageInfo

func (m *DefaultPaymentMethodRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DefaultPaymentMethodResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefaultPaymentMethodResponse) Reset()         { *m = DefaultPaymentMethodResponse{} }
func (m *DefaultPaymentMethodResponse) String() string { return proto.CompactTextString(m) }
func (*DefaultPaymentMethodResponse) ProtoMessage()    {}
func (*DefaultPaymentMethodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{22}
}

func (m *DefaultPaymentMethodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultPaymentMethodResponse.Unmarshal(m, b)
}
func (m *DefaultPaymentMethodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultPaymentMethodResponse.Marshal(b, m, deterministic)
}
func (m *DefaultPaymentMethodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultPaymentMethodResponse.Merge(m, src)
}
func (m *DefaultPaymentMethodResponse) XXX_Size() int {
	return xxx_messageInfo_DefaultPaymentMethodResponse.Size(m)
}
func (m *DefaultPaymentMethodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultPaymentMethodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultPaymentMethodResponse proto.InternalMessageInfo

type Environment struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string   `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Environment) Reset()         { *m = Environment{} }
func (m *Environment) String() string { return proto.CompactTextString(m) }
func (*Environment) ProtoMessage()    {}
func (*Environment) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{23}
}

func (m *Environment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Environment.Unmarshal(m, b)
}
func (m *Environment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Environment.Marshal(b, m, deterministic)
}
func (m *Environment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Environment.Merge(m, src)
}
func (m *Environment) XXX_Size() int {
	return xxx_messageInfo_Environment.Size(m)
}
func (m *Environment) XXX_DiscardUnknown() {
	xxx_messageInfo_Environment.DiscardUnknown(m)
}

var xxx_messageInfo_Environment proto.InternalMessageInfo

func (m *Environment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Environment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Environment) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Environment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateEnvironmentRequest struct {
	Environment          *Environment `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	ProjectId            string       `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateEnvironmentRequest) Reset()         { *m = CreateEnvironmentRequest{} }
func (m *CreateEnvironmentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEnvironmentRequest) ProtoMessage()    {}
func (*CreateEnvironmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{24}
}

func (m *CreateEnvironmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEnvironmentRequest.Unmarshal(m, b)
}
func (m *CreateEnvironmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEnvironmentRequest.Marshal(b, m, deterministic)
}
func (m *CreateEnvironmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEnvironmentRequest.Merge(m, src)
}
func (m *CreateEnvironmentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEnvironmentRequest.Size(m)
}
func (m *CreateEnvironmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEnvironmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEnvironmentRequest proto.InternalMessageInfo

func (m *CreateEnvironmentRequest) GetEnvironment() *Environment {
	if m != nil {
		return m.Environment
	}
	return nil
}

func (m *CreateEnvironmentRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type CreateEnvironmentResponse struct {
	Environment          *Environment `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateEnvironmentResponse) Reset()         { *m = CreateEnvironmentResponse{} }
func (m *CreateEnvironmentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEnvironmentResponse) ProtoMessage()    {}
func (*CreateEnvironmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{25}
}

func (m *CreateEnvironmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEnvironmentResponse.Unmarshal(m, b)
}
func (m *CreateEnvironmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEnvironmentResponse.Marshal(b, m, deterministic)
}
func (m *CreateEnvironmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEnvironmentResponse.Merge(m, src)
}
func (m *CreateEnvironmentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEnvironmentResponse.Size(m)
}
func (m *CreateEnvironmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEnvironmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEnvironmentResponse proto.InternalMessageInfo

func (m *CreateEnvironmentResponse) GetEnvironment() *Environment {
	if m != nil {
		return m.Environment
	}
	return nil
}

type UpdateEnvironmentRequest struct {
	Environment          *Environment `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateEnvironmentRequest) Reset()         { *m = UpdateEnvironmentRequest{} }
func (m *UpdateEnvironmentRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateEnvironmentRequest) ProtoMessage()    {}
func (*UpdateEnvironmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{26}
}

func (m *UpdateEnvironmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEnvironmentRequest.Unmarshal(m, b)
}
func (m *UpdateEnvironmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEnvironmentRequest.Marshal(b, m, deterministic)
}
func (m *UpdateEnvironmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEnvironmentRequest.Merge(m, src)
}
func (m *UpdateEnvironmentRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateEnvironmentRequest.Size(m)
}
func (m *UpdateEnvironmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEnvironmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEnvironmentRequest proto.InternalMessageInfo

func (m *UpdateEnvironmentRequest) GetEnvironment() *Environment {
	if m != nil {
		return m.Environment
	}
	return nil
}

type UpdateEnvironmentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEnvironmentResponse) Reset()         { *m = UpdateEnvironmentResponse{} }
func (m *UpdateEnvironmentResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateEnvironmentResponse) ProtoMessage()    {}
func (*UpdateEnvironmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{27}
}

func (m *UpdateEnvironmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEnvironmentResponse.Unmarshal(m, b)
}
func (m *UpdateEnvironmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEnvironmentResponse.Marshal(b, m, deterministic)
}
func (m *UpdateEnvironmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEnvironmentResponse.Merge(m, src)
}
func (m *UpdateEnvironmentResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateEnvironmentResponse.Size(m)
}
func (m *UpdateEnvironmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEnvironmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEnvironmentResponse proto.InternalMessageInfo

type DeleteEnvironmentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEnvironmentRequest) Reset()         { *m = DeleteEnvironmentRequest{} }
func (m *DeleteEnvironmentRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteEnvironmentRequest) ProtoMessage()    {}
func (*DeleteEnvironmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{28}
}

func (m *DeleteEnvironmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEnvironmentRequest.Unmarshal(m, b)
}
func (m *DeleteEnvironmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEnvironmentRequest.Marshal(b, m, deterministic)
}
func (m *DeleteEnvironmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEnvironmentRequest.Merge(m, src)
}
func (m *DeleteEnvironmentRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteEnvironmentRequest.Size(m)
}
func (m *DeleteEnvironmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEnvironmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEnvironmentRequest proto.InternalMessageInfo

func (m *DeleteEnvironmentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteEnvironmentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEnvironmentResponse) Reset()         { *m = DeleteEnvironmentResponse{} }
func (m *DeleteEnvironmentResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteEnvironmentResponse) ProtoMessage()    {}
func (*DeleteEnvironmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{29}
}

func (m *DeleteEnvironmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEnvironmentResponse.Unmarshal(m, b)
}
func (m *DeleteEnvironmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEnvironmentResponse.Marshal(b, m, deterministic)
}
func (m *DeleteEnvironmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEnvironmentResponse.Merge(m, src)
}
func (m *DeleteEnvironmentResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteEnvironmentResponse.Size(m)
}
func (m *DeleteEnvironmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEnvironmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEnvironmentResponse proto.InternalMessageInfo

type ValidateProjectNameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateProjectNameRequest) Reset()         { *m = ValidateProjectNameRequest{} }
func (m *ValidateProjectNameRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateProjectNameRequest) ProtoMessage()    {}
func (*ValidateProjectNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{30}
}

func (m *ValidateProjectNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateProjectNameRequest.Unmarshal(m, b)
}
func (m *ValidateProjectNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateProjectNameRequest.Marshal(b, m, deterministic)
}
func (m *ValidateProjectNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateProjectNameRequest.Merge(m, src)
}
func (m *ValidateProjectNameRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateProjectNameRequest.Size(m)
}
func (m *ValidateProjectNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateProjectNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateProjectNameRequest proto.InternalMessageInfo

func (m *ValidateProjectNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ValidateProjectNameResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateProjectNameResponse) Reset()         { *m = ValidateProjectNameResponse{} }
func (m *ValidateProjectNameResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateProjectNameResponse) ProtoMessage()    {}
func (*ValidateProjectNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{31}
}

func (m *ValidateProjectNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateProjectNameResponse.Unmarshal(m, b)
}
func (m *ValidateProjectNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateProjectNameResponse.Marshal(b, m, deterministic)
}
func (m *ValidateProjectNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateProjectNameResponse.Merge(m, src)
}
func (m *ValidateProjectNameResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateProjectNameResponse.Size(m)
}
func (m *ValidateProjectNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateProjectNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateProjectNameResponse proto.InternalMessageInfo

type ValidateEnvironmentNameRequest struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateEnvironmentNameRequest) Reset()         { *m = ValidateEnvironmentNameRequest{} }
func (m *ValidateEnvironmentNameRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateEnvironmentNameRequest) ProtoMessage()    {}
func (*ValidateEnvironmentNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{32}
}

func (m *ValidateEnvironmentNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateEnvironmentNameRequest.Unmarshal(m, b)
}
func (m *ValidateEnvironmentNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateEnvironmentNameRequest.Marshal(b, m, deterministic)
}
func (m *ValidateEnvironmentNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateEnvironmentNameRequest.Merge(m, src)
}
func (m *ValidateEnvironmentNameRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateEnvironmentNameRequest.Size(m)
}
func (m *ValidateEnvironmentNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateEnvironmentNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateEnvironmentNameRequest proto.InternalMessageInfo

func (m *ValidateEnvironmentNameRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *ValidateEnvironmentNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ValidateEnvironmentNameResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateEnvironmentNameResponse) Reset()         { *m = ValidateEnvironmentNameResponse{} }
func (m *ValidateEnvironmentNameResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateEnvironmentNameResponse) ProtoMessage()    {}
func (*ValidateEnvironmentNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{33}
}

func (m *ValidateEnvironmentNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateEnvironmentNameResponse.Unmarshal(m, b)
}
func (m *ValidateEnvironmentNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateEnvironmentNameResponse.Marshal(b, m, deterministic)
}
func (m *ValidateEnvironmentNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateEnvironmentNameResponse.Merge(m, src)
}
func (m *ValidateEnvironmentNameResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateEnvironmentNameResponse.Size(m)
}
func (m *ValidateEnvironmentNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateEnvironmentNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateEnvironmentNameResponse proto.InternalMessageInfo

type InviteRequest struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteRequest) Reset()         { *m = InviteRequest{} }
func (m *InviteRequest) String() string { return proto.CompactTextString(m) }
func (*InviteRequest) ProtoMessage()    {}
func (*InviteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{34}
}

func (m *InviteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteRequest.Unmarshal(m, b)
}
func (m *InviteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteRequest.Marshal(b, m, deterministic)
}
func (m *InviteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteRequest.Merge(m, src)
}
func (m *InviteRequest) XXX_Size() int {
	return xxx_messageInfo_InviteRequest.Size(m)
}
func (m *InviteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InviteRequest proto.InternalMessageInfo

func (m *InviteRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *InviteRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *InviteRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type InviteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteResponse) Reset()         { *m = InviteResponse{} }
func (m *InviteResponse) String() string { return proto.CompactTextString(m) }
func (*InviteResponse) ProtoMessage()    {}
func (*InviteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{35}
}

func (m *InviteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteResponse.Unmarshal(m, b)
}
func (m *InviteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteResponse.Marshal(b, m, deterministic)
}
func (m *InviteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteResponse.Merge(m, src)
}
func (m *InviteResponse) XXX_Size() int {
	return xxx_messageInfo_InviteResponse.Size(m)
}
func (m *InviteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InviteResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*User)(nil), "go.micro.api.m3o.User")
	proto.RegisterType((*ReadAccountRequest)(nil), "go.micro.api.m3o.ReadAccountRequest")
	proto.RegisterType((*ReadAccountResponse)(nil), "go.micro.api.m3o.ReadAccountResponse")
	proto.RegisterType((*Project)(nil), "go.micro.api.m3o.Project")
	proto.RegisterType((*Member)(nil), "go.micro.api.m3o.Member")
	proto.RegisterType((*CreateProjectRequest)(nil), "go.micro.api.m3o.CreateProjectRequest")
	proto.RegisterType((*CreateProjectResponse)(nil), "go.micro.api.m3o.CreateProjectResponse")
	proto.RegisterType((*UpdateProjectRequest)(nil), "go.micro.api.m3o.UpdateProjectRequest")
	proto.RegisterType((*UpdateProjectResponse)(nil), "go.micro.api.m3o.UpdateProjectResponse")
	proto.RegisterType((*ListProjectsRequest)(nil), "go.micro.api.m3o.ListProjectsRequest")
	proto.RegisterType((*ListProjectsResponse)(nil), "go.micro.api.m3o.ListProjectsResponse")
	proto.RegisterType((*ValidateGithubTokenRequest)(nil), "go.micro.api.m3o.ValidateGithubTokenRequest")
	proto.RegisterType((*ValidateGithubTokenResponse)(nil), "go.micro.api.m3o.ValidateGithubTokenResponse")
	proto.RegisterType((*WebhookAPIKeyRequest)(nil), "go.micro.api.m3o.WebhookAPIKeyRequest")
	proto.RegisterType((*WebhookAPIKeyResponse)(nil), "go.micro.api.m3o.WebhookAPIKeyResponse")
	proto.RegisterType((*Repository)(nil), "go.micro.api.m3o.Repository")
	proto.RegisterType((*PaymentMethod)(nil), "go.micro.api.m3o.PaymentMethod")
	proto.RegisterType((*CreatePaymentMethodRequest)(nil), "go.micro.api.m3o.CreatePaymentMethodRequest")
	proto.RegisterType((*CreatePaymentMethodResponse)(nil), "go.micro.api.m3o.CreatePaymentMethodResponse")
	proto.RegisterType((*DeletePaymentMethodRequest)(nil), "go.micro.api.m3o.DeletePaymentMethodRequest")
	proto.RegisterType((*DeletePaymentMethodResponse)(nil), "go.micro.api.m3o.DeletePaymentMethodResponse")
	proto.RegisterType((*DefaultPaymentMethodRequest)(nil), "go.micro.api.m3o.DefaultPaymentMethodRequest")
	proto.RegisterType((*DefaultPaymentMethodResponse)(nil), "go.micro.api.m3o.DefaultPaymentMethodResponse")
	proto.RegisterType((*Environment)(nil), "go.micro.api.m3o.Environment")
	proto.RegisterType((*CreateEnvironmentRequest)(nil), "go.micro.api.m3o.CreateEnvironmentRequest")
	proto.RegisterType((*CreateEnvironmentResponse)(nil), "go.micro.api.m3o.CreateEnvironmentResponse")
	proto.RegisterType((*UpdateEnvironmentRequest)(nil), "go.micro.api.m3o.UpdateEnvironmentRequest")
	proto.RegisterType((*UpdateEnvironmentResponse)(nil), "go.micro.api.m3o.UpdateEnvironmentResponse")
	proto.RegisterType((*DeleteEnvironmentRequest)(nil), "go.micro.api.m3o.DeleteEnvironmentRequest")
	proto.RegisterType((*DeleteEnvironmentResponse)(nil), "go.micro.api.m3o.DeleteEnvironmentResponse")
	proto.RegisterType((*ValidateProjectNameRequest)(nil), "go.micro.api.m3o.ValidateProjectNameRequest")
	proto.RegisterType((*ValidateProjectNameResponse)(nil), "go.micro.api.m3o.ValidateProjectNameResponse")
	proto.RegisterType((*ValidateEnvironmentNameRequest)(nil), "go.micro.api.m3o.ValidateEnvironmentNameRequest")
	proto.RegisterType((*ValidateEnvironmentNameResponse)(nil), "go.micro.api.m3o.ValidateEnvironmentNameResponse")
	proto.RegisterType((*InviteRequest)(nil), "go.micro.api.m3o.InviteRequest")
	proto.RegisterType((*InviteResponse)(nil), "go.micro.api.m3o.InviteResponse")
}

func init() {
	proto.RegisterFile("github.com/micro/services/m3o/api/proto/m3o.proto", fileDescriptor_adee7567aa95c263)
}

var fileDescriptor_adee7567aa95c263 = []byte{
	// 1247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0xdd, 0x72, 0xdb, 0xc4,
	0x17, 0xb7, 0x1d, 0x27, 0xb1, 0x8f, 0xe3, 0xfc, 0xdb, 0x8d, 0xf3, 0xaf, 0x22, 0x37, 0x69, 0xba,
	0x94, 0xd2, 0x09, 0xad, 0xd3, 0x3a, 0xed, 0x0d, 0x37, 0x4c, 0x80, 0x02, 0x99, 0x36, 0x4c, 0x50,
	0x09, 0xd0, 0x81, 0x19, 0x8f, 0x2c, 0x6d, 0x1a, 0x51, 0xeb, 0xa3, 0x2b, 0x39, 0x34, 0x5c, 0x30,
	0x3c, 0x01, 0x4f, 0xc1, 0xb3, 0xf0, 0x14, 0x5c, 0x71, 0xc1, 0x73, 0x30, 0xda, 0x3d, 0xb2, 0xf5,
	0xb1, 0xb2, 0x5d, 0xbe, 0xae, 0xa2, 0x3d, 0xfb, 0xdb, 0xf3, 0x3b, 0x7b, 0xf6, 0x7c, 0xc5, 0xf0,
	0xe0, 0x85, 0x13, 0x9d, 0x8f, 0x87, 0x3d, 0xcb, 0x77, 0xf7, 0x5d, 0xc7, 0xe2, 0xfe, 0x7e, 0xc8,
	0xf8, 0x85, 0x63, 0xb1, 0x70, 0xdf, 0x3d, 0xf0, 0xf7, 0xcd, 0xc0, 0xd9, 0x0f, 0xb8, 0x1f, 0xf9,
	0xf1, 0xaa, 0x27, 0xbe, 0xc8, 0x95, 0x17, 0x7e, 0x4f, 0x40, 0x7b, 0x66, 0xe0, 0xf4, 0xdc, 0x03,
	0x9f, 0xfe, 0x5e, 0x85, 0xfa, 0x69, 0xc8, 0x38, 0x59, 0x87, 0x9a, 0x63, 0x6b, 0xd5, 0xdd, 0xea,
	0x9d, 0xa6, 0x51, 0x73, 0x6c, 0xb2, 0x0d, 0x70, 0xe6, 0xf0, 0x30, 0x1a, 0x78, 0xa6, 0xcb, 0xb4,
	0x9a, 0x90, 0x37, 0x85, 0xe4, 0x33, 0xd3, 0x65, 0xa4, 0x0b, 0xcd, 0x91, 0x99, 0xec, 0x2e, 0x89,
	0xdd, 0x46, 0x2c, 0x10, 0x9b, 0x1d, 0x58, 0x66, 0xae, 0xe9, 0x8c, 0xb4, 0xba, 0xd8, 0x90, 0x0b,
	0xd2, 0x83, 0x8d, 0x80, 0xfb, 0x67, 0xce, 0x88, 0x0d, 0x02, 0xc7, 0x8a, 0xc6, 0x9c, 0x0d, 0xc6,
	0x7c, 0xa4, 0x2d, 0x0b, 0xcc, 0x55, 0xdc, 0x3a, 0x91, 0x3b, 0xa7, 0x7c, 0x44, 0x3e, 0x85, 0xff,
	0x05, 0xe6, 0xa5, 0xcb, 0xbc, 0x68, 0xe0, 0xb2, 0xe8, 0xdc, 0xb7, 0x43, 0x6d, 0x65, 0x77, 0xe9,
	0x4e, 0xab, 0x7f, 0xa3, 0x97, 0xbf, 0x46, 0xef, 0x44, 0x02, 0x8f, 0x05, 0xce, 0x58, 0x0f, 0xd2,
	0xcb, 0x90, 0x76, 0x80, 0x18, 0xcc, 0xb4, 0x0f, 0x2d, 0xcb, 0x1f, 0x7b, 0x91, 0xc1, 0x5e, 0x8d,
	0x59, 0x18, 0xd1, 0x43, 0xd8, 0xc8, 0x48, 0xc3, 0xc0, 0xf7, 0x42, 0x46, 0xf6, 0xa0, 0x3e, 0x0e,
	0x19, 0x17, 0xae, 0x68, 0xf5, 0xff, 0x5f, 0xe4, 0x8a, 0xdd, 0x65, 0x08, 0x0c, 0xfd, 0xa3, 0x0a,
	0xab, 0x27, 0xdc, 0xff, 0x8e, 0x59, 0x51, 0xc1, 0x81, 0x04, 0xea, 0x29, 0xd7, 0x89, 0x6f, 0xb2,
	0x0b, 0x2d, 0x9b, 0x85, 0x16, 0x77, 0x82, 0xc8, 0xf1, 0x3d, 0xf4, 0x5b, 0x5a, 0x44, 0x76, 0x00,
	0x38, 0x0b, 0xfc, 0xd0, 0x89, 0x7c, 0x7e, 0x89, 0xfe, 0x4b, 0x49, 0xc8, 0x21, 0xac, 0x31, 0xef,
	0xc2, 0xe1, 0xbe, 0x17, 0x5f, 0x30, 0xd4, 0x96, 0x85, 0x47, 0xb6, 0x8b, 0x56, 0x3e, 0x9e, 0xa2,
	0x8c, 0xcc, 0x11, 0xd2, 0x87, 0x55, 0x97, 0xb9, 0x43, 0xc6, 0x13, 0x7f, 0x6a, 0xc5, 0xd3, 0xc7,
	0x02, 0x60, 0x24, 0x40, 0xfa, 0x23, 0xac, 0x48, 0xd1, 0x7f, 0x10, 0x27, 0x04, 0xea, 0xdc, 0x1f,
	0x31, 0x0c, 0x0c, 0xf1, 0x4d, 0x3d, 0xe8, 0x7c, 0xc8, 0x99, 0x19, 0x31, 0xf4, 0x36, 0xbe, 0x21,
	0x39, 0x80, 0xd5, 0x40, 0x4a, 0xf0, 0xbd, 0xb6, 0x14, 0xb1, 0x81, 0x47, 0x12, 0x24, 0xb9, 0x09,
	0x6b, 0x32, 0x75, 0x06, 0x91, 0xff, 0x92, 0x79, 0x68, 0x74, 0x4b, 0xca, 0xbe, 0x88, 0x45, 0xf4,
	0xe7, 0x2a, 0x6c, 0xe6, 0x08, 0x31, 0x3c, 0xfe, 0x12, 0x63, 0x17, 0x9a, 0xd6, 0xc8, 0x89, 0x23,
	0xd9, 0xb1, 0x91, 0xae, 0x21, 0x05, 0x47, 0x36, 0x79, 0x0b, 0xda, 0xb8, 0x19, 0x32, 0x8b, 0xb3,
	0x08, 0xdd, 0xb4, 0x26, 0x85, 0xcf, 0x84, 0x8c, 0x3e, 0x81, 0xce, 0x69, 0x60, 0xff, 0x33, 0x0e,
	0xa0, 0xd7, 0x60, 0x33, 0xa7, 0x4c, 0x5e, 0x8e, 0x6e, 0xc2, 0xc6, 0x53, 0x27, 0x8c, 0x50, 0x1c,
	0x26, 0x99, 0x72, 0x0c, 0x9d, 0xac, 0x18, 0x7d, 0xf1, 0x08, 0x1a, 0xa8, 0x32, 0xd4, 0xaa, 0x22,
	0x94, 0x66, 0xb0, 0x4f, 0xa0, 0xb4, 0x0f, 0xfa, 0x97, 0xe6, 0xc8, 0x89, 0x0d, 0xf8, 0x64, 0xea,
	0xf3, 0xe4, 0x46, 0x1d, 0x58, 0x96, 0xcf, 0x22, 0x63, 0x4c, 0x2e, 0xe8, 0xe7, 0xd0, 0x55, 0x9e,
	0x41, 0x4b, 0xfa, 0xb0, 0x2c, 0x92, 0x04, 0xcd, 0xb8, 0x5e, 0x34, 0xc3, 0x98, 0xe4, 0x90, 0x21,
	0xa1, 0xf4, 0x11, 0x74, 0xbe, 0x62, 0xc3, 0x73, 0xdf, 0x7f, 0x79, 0x78, 0x72, 0xf4, 0x84, 0x5d,
	0x26, 0x06, 0x6c, 0x03, 0xa0, 0xa9, 0x83, 0x49, 0xa4, 0x37, 0x51, 0x72, 0x64, 0xd3, 0xe7, 0xb0,
	0x99, 0x3b, 0x86, 0x36, 0x64, 0x1e, 0xb9, 0x3a, 0xef, 0x91, 0x6b, 0x8a, 0x47, 0x7e, 0x0f, 0x60,
	0x6a, 0xe6, 0xa4, 0x80, 0x54, 0x53, 0x05, 0x44, 0x8b, 0x9f, 0xdb, 0xb9, 0x30, 0x23, 0x99, 0x6a,
	0x0d, 0x23, 0x59, 0xd2, 0xdf, 0xaa, 0xd0, 0xce, 0x54, 0xc1, 0x42, 0xa6, 0x6a, 0xb0, 0x6a, 0x89,
	0x90, 0x96, 0x21, 0xb8, 0x64, 0x24, 0xcb, 0xf8, 0xc6, 0x96, 0xc9, 0xed, 0xc1, 0x90, 0x9b, 0x9e,
	0x8d, 0xe1, 0xd7, 0x8c, 0x25, 0x1f, 0xc4, 0x02, 0x72, 0x0b, 0xd6, 0xc5, 0x36, 0x7b, 0x1d, 0x0c,
	0x5c, 0xdf, 0x8b, 0xce, 0x31, 0x5f, 0xd7, 0x62, 0xe9, 0xe3, 0xd7, 0xc1, 0x71, 0x2c, 0x23, 0x14,
	0xda, 0x13, 0xd4, 0x25, 0x33, 0x39, 0xe6, 0x6f, 0x0b, 0x41, 0xcf, 0x99, 0xc9, 0xc9, 0x0e, 0x88,
	0xe5, 0x40, 0x94, 0x84, 0x87, 0xda, 0xca, 0x94, 0xe9, 0xa9, 0x19, 0x46, 0x0f, 0x63, 0x13, 0x6d,
	0x76, 0x66, 0x8e, 0x47, 0x91, 0xb6, 0x2a, 0xaf, 0x87, 0x4b, 0x7a, 0x17, 0x74, 0xcc, 0xc7, 0x4c,
	0xa5, 0xc7, 0x27, 0xcb, 0x5d, 0x95, 0x32, 0xe8, 0x2a, 0xd1, 0xf8, 0x52, 0x1f, 0xc3, 0x7a, 0xb6,
	0xb3, 0x60, 0xee, 0xcc, 0x6d, 0x2c, 0xed, 0x4c, 0x63, 0x89, 0x8d, 0xfa, 0x88, 0x8d, 0xd8, 0x82,
	0x46, 0x6d, 0x43, 0x57, 0x89, 0xc6, 0xdc, 0xbb, 0x17, 0x6f, 0x8b, 0xcb, 0x2e, 0xa4, 0x6d, 0x07,
	0xae, 0xab, 0xe1, 0xa8, 0xee, 0x15, 0xb4, 0x52, 0x2d, 0x60, 0xa1, 0xee, 0x74, 0x1d, 0x9a, 0xf1,
	0xdf, 0x30, 0x30, 0xad, 0xa4, 0x56, 0x4f, 0x05, 0xf9, 0xde, 0x55, 0x2f, 0xf4, 0x2e, 0xfa, 0x03,
	0x68, 0xd2, 0xeb, 0xe9, 0xde, 0x83, 0xe6, 0xbf, 0x0f, 0xad, 0x54, 0x13, 0x42, 0x7f, 0xcf, 0x69,
	0x5b, 0xe9, 0x13, 0xb9, 0xac, 0xac, 0xe5, 0xb3, 0xf2, 0x5b, 0xd8, 0x52, 0x70, 0xe3, 0x7b, 0xff,
	0x5d, 0x72, 0xfa, 0x0d, 0x68, 0xb2, 0x60, 0xfe, 0x0b, 0x37, 0xa3, 0x5d, 0xd8, 0x52, 0x28, 0xc7,
	0x67, 0xdc, 0x03, 0x4d, 0x06, 0x8d, 0x82, 0x39, 0x1f, 0x12, 0x5d, 0xd8, 0x52, 0x60, 0x51, 0xd1,
	0xfd, 0x69, 0xd1, 0xc5, 0x8a, 0x1c, 0xb7, 0xe0, 0x44, 0x95, 0xa2, 0xd6, 0xc4, 0xf1, 0xaa, 0x3c,
	0x81, 0x0a, 0x9f, 0xc1, 0x4e, 0xb2, 0x9d, 0xe2, 0x4b, 0x2b, 0x9d, 0x5d, 0x48, 0x55, 0x21, 0x48,
	0x6f, 0xc2, 0x8d, 0x52, 0xa5, 0xc8, 0xfb, 0x35, 0xb4, 0x8f, 0xbc, 0x0b, 0x27, 0x5a, 0x94, 0x66,
	0x32, 0x64, 0xd4, 0x72, 0x43, 0x46, 0x6a, 0x24, 0x91, 0xe4, 0x57, 0x60, 0x3d, 0xd1, 0x2c, 0xb9,
	0xfa, 0xbf, 0x2e, 0x41, 0x03, 0xe7, 0xc3, 0x90, 0x9c, 0x42, 0x3d, 0x9e, 0x17, 0xc9, 0x2d, 0x55,
	0x73, 0xc9, 0x4f, 0x97, 0xfa, 0xdb, 0x73, 0x50, 0x78, 0x9b, 0x0a, 0x89, 0x60, 0x43, 0x51, 0xab,
	0xc8, 0xdd, 0xe2, 0xf9, 0xf2, 0x02, 0xa8, 0xdf, 0x5b, 0x10, 0x9d, 0x66, 0x55, 0x14, 0x23, 0x15,
	0x6b, 0x79, 0x85, 0x53, 0xb1, 0xce, 0xaa, 0x70, 0x15, 0xf2, 0x3d, 0x74, 0x54, 0x45, 0x8b, 0x28,
	0x15, 0x95, 0xd6, 0x42, 0xbd, 0xb7, 0x28, 0x3c, 0x21, 0xee, 0xff, 0xd2, 0x84, 0x46, 0x32, 0xbe,
	0xc4, 0x77, 0x57, 0xcc, 0x12, 0xaa, 0xbb, 0x97, 0x8f, 0x29, 0xaa, 0xbb, 0xcf, 0x18, 0x50, 0xa4,
	0xc7, 0x15, 0xe9, 0x34, 0x8b, 0xb5, 0x98, 0xa7, 0xb3, 0x58, 0x55, 0x39, 0x5a, 0x21, 0x3f, 0x55,
	0xe1, 0x5a, 0x49, 0x46, 0x91, 0xfb, 0xe5, 0xca, 0xd4, 0x19, 0xad, 0x3f, 0x78, 0x83, 0x13, 0x13,
	0x13, 0x86, 0xd0, 0xce, 0x0c, 0x4c, 0xe4, 0x76, 0x51, 0x8b, 0x6a, 0x10, 0xd3, 0xdf, 0x99, 0x8b,
	0x4b, 0x73, 0x64, 0xc6, 0x75, 0x15, 0x87, 0xea, 0x1f, 0x08, 0x15, 0x87, 0x72, 0xee, 0x97, 0x1c,
	0x99, 0xa9, 0x59, 0xc5, 0xa1, 0x9a, 0xd1, 0x55, 0x1c, 0xea, 0xf1, 0xbb, 0x42, 0x06, 0xb0, 0x96,
	0x9e, 0xb4, 0x89, 0xa2, 0x8a, 0x28, 0x06, 0x74, 0xfd, 0xf6, 0x3c, 0xd8, 0x84, 0xc0, 0x83, 0xab,
	0x85, 0x3e, 0x49, 0xf6, 0xca, 0x9c, 0x50, 0x6c, 0x3a, 0xfa, 0xbb, 0x0b, 0x61, 0xd3, 0x7c, 0x85,
	0xe6, 0xa6, 0xe2, 0x2b, 0x6b, 0xaf, 0x2a, 0xbe, 0xf2, 0x6e, 0x59, 0x21, 0x2e, 0x5c, 0x2d, 0xf4,
	0x40, 0x15, 0x5f, 0x59, 0x53, 0xd5, 0xdf, 0x00, 0x4b, 0x2b, 0xe4, 0x18, 0x56, 0x64, 0xcb, 0x20,
	0x8a, 0xd9, 0x31, 0xd3, 0xa6, 0xf4, 0xdd, 0x72, 0x40, 0x62, 0xfd, 0x70, 0x45, 0xfc, 0x4c, 0x73,
	0xf0, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x89, 0x4e, 0x02, 0xdb, 0x11, 0x00, 0x00,
}
