// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: github.com/micro/services/explore/proto/explore/explore.proto

package go_micro_srv_explore

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Explore service

type ExploreService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Explore_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Explore_PingPongService, error)
}

type exploreService struct {
	c    client.Client
	name string
}

func NewExploreService(name string, c client.Client) ExploreService {
	return &exploreService{
		c:    c,
		name: name,
	}
}

func (c *exploreService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Explore.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exploreService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Explore_StreamService, error) {
	req := c.c.NewRequest(c.name, "Explore.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &exploreServiceStream{stream}, nil
}

type Explore_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type exploreServiceStream struct {
	stream client.Stream
}

func (x *exploreServiceStream) Close() error {
	return x.stream.Close()
}

func (x *exploreServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *exploreServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *exploreServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *exploreServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *exploreService) PingPong(ctx context.Context, opts ...client.CallOption) (Explore_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Explore.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &exploreServicePingPong{stream}, nil
}

type Explore_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type exploreServicePingPong struct {
	stream client.Stream
}

func (x *exploreServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *exploreServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *exploreServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *exploreServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *exploreServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *exploreServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Explore service

type ExploreHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Explore_StreamStream) error
	PingPong(context.Context, Explore_PingPongStream) error
}

func RegisterExploreHandler(s server.Server, hdlr ExploreHandler, opts ...server.HandlerOption) error {
	type explore interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Explore struct {
		explore
	}
	h := &exploreHandler{hdlr}
	return s.Handle(s.NewHandler(&Explore{h}, opts...))
}

type exploreHandler struct {
	ExploreHandler
}

func (h *exploreHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ExploreHandler.Call(ctx, in, out)
}

func (h *exploreHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ExploreHandler.Stream(ctx, m, &exploreStreamStream{stream})
}

type Explore_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type exploreStreamStream struct {
	stream server.Stream
}

func (x *exploreStreamStream) Close() error {
	return x.stream.Close()
}

func (x *exploreStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *exploreStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *exploreStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *exploreStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *exploreHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.ExploreHandler.PingPong(ctx, &explorePingPongStream{stream})
}

type Explore_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type explorePingPongStream struct {
	stream server.Stream
}

func (x *explorePingPongStream) Close() error {
	return x.stream.Close()
}

func (x *explorePingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *explorePingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *explorePingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *explorePingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *explorePingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
