// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/notes/notes.proto

package go_micro_api_notes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Notes service

type NotesService interface {
	CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...client.CallOption) (*CreateNoteResponse, error)
	UpdateNote(ctx context.Context, in *UpdateNoteRequest, opts ...client.CallOption) (*UpdateNoteResponse, error)
	DeleteNote(ctx context.Context, in *DeleteNoteRequest, opts ...client.CallOption) (*DeleteNoteResponse, error)
	ListNotes(ctx context.Context, in *ListNotesRequest, opts ...client.CallOption) (*ListNotesResponse, error)
}

type notesService struct {
	c    client.Client
	name string
}

func NewNotesService(name string, c client.Client) NotesService {
	return &notesService{
		c:    c,
		name: name,
	}
}

func (c *notesService) CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...client.CallOption) (*CreateNoteResponse, error) {
	req := c.c.NewRequest(c.name, "Notes.CreateNote", in)
	out := new(CreateNoteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notesService) UpdateNote(ctx context.Context, in *UpdateNoteRequest, opts ...client.CallOption) (*UpdateNoteResponse, error) {
	req := c.c.NewRequest(c.name, "Notes.UpdateNote", in)
	out := new(UpdateNoteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notesService) DeleteNote(ctx context.Context, in *DeleteNoteRequest, opts ...client.CallOption) (*DeleteNoteResponse, error) {
	req := c.c.NewRequest(c.name, "Notes.DeleteNote", in)
	out := new(DeleteNoteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notesService) ListNotes(ctx context.Context, in *ListNotesRequest, opts ...client.CallOption) (*ListNotesResponse, error) {
	req := c.c.NewRequest(c.name, "Notes.ListNotes", in)
	out := new(ListNotesResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Notes service

type NotesHandler interface {
	CreateNote(context.Context, *CreateNoteRequest, *CreateNoteResponse) error
	UpdateNote(context.Context, *UpdateNoteRequest, *UpdateNoteResponse) error
	DeleteNote(context.Context, *DeleteNoteRequest, *DeleteNoteResponse) error
	ListNotes(context.Context, *ListNotesRequest, *ListNotesResponse) error
}

func RegisterNotesHandler(s server.Server, hdlr NotesHandler, opts ...server.HandlerOption) error {
	type notes interface {
		CreateNote(ctx context.Context, in *CreateNoteRequest, out *CreateNoteResponse) error
		UpdateNote(ctx context.Context, in *UpdateNoteRequest, out *UpdateNoteResponse) error
		DeleteNote(ctx context.Context, in *DeleteNoteRequest, out *DeleteNoteResponse) error
		ListNotes(ctx context.Context, in *ListNotesRequest, out *ListNotesResponse) error
	}
	type Notes struct {
		notes
	}
	h := &notesHandler{hdlr}
	return s.Handle(s.NewHandler(&Notes{h}, opts...))
}

type notesHandler struct {
	NotesHandler
}

func (h *notesHandler) CreateNote(ctx context.Context, in *CreateNoteRequest, out *CreateNoteResponse) error {
	return h.NotesHandler.CreateNote(ctx, in, out)
}

func (h *notesHandler) UpdateNote(ctx context.Context, in *UpdateNoteRequest, out *UpdateNoteResponse) error {
	return h.NotesHandler.UpdateNote(ctx, in, out)
}

func (h *notesHandler) DeleteNote(ctx context.Context, in *DeleteNoteRequest, out *DeleteNoteResponse) error {
	return h.NotesHandler.DeleteNote(ctx, in, out)
}

func (h *notesHandler) ListNotes(ctx context.Context, in *ListNotesRequest, out *ListNotesResponse) error {
	return h.NotesHandler.ListNotes(ctx, in, out)
}
