// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/micro/services/platform/service/proto/platform.proto

package go_micro_service_platform

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventType int32

const (
	EventType_Unknown        EventType = 0
	EventType_ServiceCreated EventType = 1
	EventType_ServiceDeleted EventType = 2
	EventType_ServiceUpdated EventType = 3
	EventType_BuildStarted   EventType = 5
	EventType_BuildFinished  EventType = 6
	EventType_BuildFailed    EventType = 7
	EventType_SourceCreated  EventType = 4
	EventType_SourceUpdated  EventType = 8
	EventType_SourceDeleted  EventType = 9
)

var EventType_name = map[int32]string{
	0: "Unknown",
	1: "ServiceCreated",
	2: "ServiceDeleted",
	3: "ServiceUpdated",
	5: "BuildStarted",
	6: "BuildFinished",
	7: "BuildFailed",
	4: "SourceCreated",
	8: "SourceUpdated",
	9: "SourceDeleted",
}

var EventType_value = map[string]int32{
	"Unknown":        0,
	"ServiceCreated": 1,
	"ServiceDeleted": 2,
	"ServiceUpdated": 3,
	"BuildStarted":   5,
	"BuildFinished":  6,
	"BuildFailed":    7,
	"SourceCreated":  4,
	"SourceUpdated":  8,
	"SourceDeleted":  9,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0f1c22ef5972cd4b, []int{0}
}

type Status struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1c22ef5972cd4b, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Status) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *Status) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1c22ef5972cd4b, []int{1}
}

func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusResponse struct {
	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// The status of each service
	Runtime              map[string]*Status `protobuf:"bytes,2,rep,name=runtime,proto3" json:"runtime,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1c22ef5972cd4b, []int{2}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *StatusResponse) GetRuntime() map[string]*Status {
	if m != nil {
		return m.Runtime
	}
	return nil
}

type CreateEventRequest struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEventRequest) Reset()         { *m = CreateEventRequest{} }
func (m *CreateEventRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEventRequest) ProtoMessage()    {}
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1c22ef5972cd4b, []int{3}
}

func (m *CreateEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventRequest.Unmarshal(m, b)
}
func (m *CreateEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventRequest.Marshal(b, m, deterministic)
}
func (m *CreateEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventRequest.Merge(m, src)
}
func (m *CreateEventRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEventRequest.Size(m)
}
func (m *CreateEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventRequest proto.InternalMessageInfo

func (m *CreateEventRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type CreateEventResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEventResponse) Reset()         { *m = CreateEventResponse{} }
func (m *CreateEventResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEventResponse) ProtoMessage()    {}
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1c22ef5972cd4b, []int{4}
}

func (m *CreateEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventResponse.Unmarshal(m, b)
}
func (m *CreateEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventResponse.Marshal(b, m, deterministic)
}
func (m *CreateEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventResponse.Merge(m, src)
}
func (m *CreateEventResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEventResponse.Size(m)
}
func (m *CreateEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventResponse proto.InternalMessageInfo

type GetEventRequest struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventRequest) Reset()         { *m = GetEventRequest{} }
func (m *GetEventRequest) String() string { return proto.CompactTextString(m) }
func (*GetEventRequest) ProtoMessage()    {}
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1c22ef5972cd4b, []int{5}
}

func (m *GetEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventRequest.Unmarshal(m, b)
}
func (m *GetEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventRequest.Marshal(b, m, deterministic)
}
func (m *GetEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventRequest.Merge(m, src)
}
func (m *GetEventRequest) XXX_Size() int {
	return xxx_messageInfo_GetEventRequest.Size(m)
}
func (m *GetEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventRequest proto.InternalMessageInfo

func (m *GetEventRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type GetEventResponse struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventResponse) Reset()         { *m = GetEventResponse{} }
func (m *GetEventResponse) String() string { return proto.CompactTextString(m) }
func (*GetEventResponse) ProtoMessage()    {}
func (*GetEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1c22ef5972cd4b, []int{6}
}

func (m *GetEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventResponse.Unmarshal(m, b)
}
func (m *GetEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventResponse.Marshal(b, m, deterministic)
}
func (m *GetEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventResponse.Merge(m, src)
}
func (m *GetEventResponse) XXX_Size() int {
	return xxx_messageInfo_GetEventResponse.Size(m)
}
func (m *GetEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventResponse proto.InternalMessageInfo

func (m *GetEventResponse) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type ListEventsRequest struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEventsRequest) Reset()         { *m = ListEventsRequest{} }
func (m *ListEventsRequest) String() string { return proto.CompactTextString(m) }
func (*ListEventsRequest) ProtoMessage()    {}
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1c22ef5972cd4b, []int{7}
}

func (m *ListEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventsRequest.Unmarshal(m, b)
}
func (m *ListEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventsRequest.Marshal(b, m, deterministic)
}
func (m *ListEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventsRequest.Merge(m, src)
}
func (m *ListEventsRequest) XXX_Size() int {
	return xxx_messageInfo_ListEventsRequest.Size(m)
}
func (m *ListEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventsRequest proto.InternalMessageInfo

func (m *ListEventsRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type ListEventsResponse struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEventsResponse) Reset()         { *m = ListEventsResponse{} }
func (m *ListEventsResponse) String() string { return proto.CompactTextString(m) }
func (*ListEventsResponse) ProtoMessage()    {}
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1c22ef5972cd4b, []int{8}
}

func (m *ListEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventsResponse.Unmarshal(m, b)
}
func (m *ListEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventsResponse.Marshal(b, m, deterministic)
}
func (m *ListEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventsResponse.Merge(m, src)
}
func (m *ListEventsResponse) XXX_Size() int {
	return xxx_messageInfo_ListEventsResponse.Size(m)
}
func (m *ListEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventsResponse proto.InternalMessageInfo

func (m *ListEventsResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type Event struct {
	Type                 EventType         `protobuf:"varint,1,opt,name=type,proto3,enum=go.micro.service.platform.EventType" json:"type,omitempty"`
	Timestamp            int64             `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Service              *Service          `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	Id                   string            `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1c22ef5972cd4b, []int{9}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_Unknown
}

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Event) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Event) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateServiceRequest struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateServiceRequest) Reset()         { *m = CreateServiceRequest{} }
func (m *CreateServiceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateServiceRequest) ProtoMessage()    {}
func (*CreateServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1c22ef5972cd4b, []int{10}
}

func (m *CreateServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateServiceRequest.Unmarshal(m, b)
}
func (m *CreateServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateServiceRequest.Marshal(b, m, deterministic)
}
func (m *CreateServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateServiceRequest.Merge(m, src)
}
func (m *CreateServiceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateServiceRequest.Size(m)
}
func (m *CreateServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateServiceRequest proto.InternalMessageInfo

func (m *CreateServiceRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type CreateServiceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateServiceResponse) Reset()         { *m = CreateServiceResponse{} }
func (m *CreateServiceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateServiceResponse) ProtoMessage()    {}
func (*CreateServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1c22ef5972cd4b, []int{11}
}

func (m *CreateServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateServiceResponse.Unmarshal(m, b)
}
func (m *CreateServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateServiceResponse.Marshal(b, m, deterministic)
}
func (m *CreateServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateServiceResponse.Merge(m, src)
}
func (m *CreateServiceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateServiceResponse.Size(m)
}
func (m *CreateServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateServiceResponse proto.InternalMessageInfo

type ReadServiceRequest struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadServiceRequest) Reset()         { *m = ReadServiceRequest{} }
func (m *ReadServiceRequest) String() string { return proto.CompactTextString(m) }
func (*ReadServiceRequest) ProtoMessage()    {}
func (*ReadServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1c22ef5972cd4b, []int{12}
}

func (m *ReadServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadServiceRequest.Unmarshal(m, b)
}
func (m *ReadServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadServiceRequest.Marshal(b, m, deterministic)
}
func (m *ReadServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadServiceRequest.Merge(m, src)
}
func (m *ReadServiceRequest) XXX_Size() int {
	return xxx_messageInfo_ReadServiceRequest.Size(m)
}
func (m *ReadServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadServiceRequest proto.InternalMessageInfo

func (m *ReadServiceRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type ReadServiceResponse struct {
	Services             []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReadServiceResponse) Reset()         { *m = ReadServiceResponse{} }
func (m *ReadServiceResponse) String() string { return proto.CompactTextString(m) }
func (*ReadServiceResponse) ProtoMessage()    {}
func (*ReadServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1c22ef5972cd4b, []int{13}
}

func (m *ReadServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadServiceResponse.Unmarshal(m, b)
}
func (m *ReadServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadServiceResponse.Marshal(b, m, deterministic)
}
func (m *ReadServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadServiceResponse.Merge(m, src)
}
func (m *ReadServiceResponse) XXX_Size() int {
	return xxx_messageInfo_ReadServiceResponse.Size(m)
}
func (m *ReadServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadServiceResponse proto.InternalMessageInfo

func (m *ReadServiceResponse) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type UpdateServiceRequest struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateServiceRequest) Reset()         { *m = UpdateServiceRequest{} }
func (m *UpdateServiceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateServiceRequest) ProtoMessage()    {}
func (*UpdateServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1c22ef5972cd4b, []int{14}
}

func (m *UpdateServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateServiceRequest.Unmarshal(m, b)
}
func (m *UpdateServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateServiceRequest.Marshal(b, m, deterministic)
}
func (m *UpdateServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateServiceRequest.Merge(m, src)
}
func (m *UpdateServiceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateServiceRequest.Size(m)
}
func (m *UpdateServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateServiceRequest proto.InternalMessageInfo

func (m *UpdateServiceRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type UpdateServiceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateServiceResponse) Reset()         { *m = UpdateServiceResponse{} }
func (m *UpdateServiceResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateServiceResponse) ProtoMessage()    {}
func (*UpdateServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1c22ef5972cd4b, []int{15}
}

func (m *UpdateServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateServiceResponse.Unmarshal(m, b)
}
func (m *UpdateServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateServiceResponse.Marshal(b, m, deterministic)
}
func (m *UpdateServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateServiceResponse.Merge(m, src)
}
func (m *UpdateServiceResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateServiceResponse.Size(m)
}
func (m *UpdateServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateServiceResponse proto.InternalMessageInfo

type DeleteServiceRequest struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteServiceRequest) Reset()         { *m = DeleteServiceRequest{} }
func (m *DeleteServiceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteServiceRequest) ProtoMessage()    {}
func (*DeleteServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1c22ef5972cd4b, []int{16}
}

func (m *DeleteServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteServiceRequest.Unmarshal(m, b)
}
func (m *DeleteServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteServiceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteServiceRequest.Merge(m, src)
}
func (m *DeleteServiceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteServiceRequest.Size(m)
}
func (m *DeleteServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteServiceRequest proto.InternalMessageInfo

func (m *DeleteServiceRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type DeleteServiceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteServiceResponse) Reset()         { *m = DeleteServiceResponse{} }
func (m *DeleteServiceResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteServiceResponse) ProtoMessage()    {}
func (*DeleteServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1c22ef5972cd4b, []int{17}
}

func (m *DeleteServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteServiceResponse.Unmarshal(m, b)
}
func (m *DeleteServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteServiceResponse.Marshal(b, m, deterministic)
}
func (m *DeleteServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteServiceResponse.Merge(m, src)
}
func (m *DeleteServiceResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteServiceResponse.Size(m)
}
func (m *DeleteServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteServiceResponse proto.InternalMessageInfo

type ListServicesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListServicesRequest) Reset()         { *m = ListServicesRequest{} }
func (m *ListServicesRequest) String() string { return proto.CompactTextString(m) }
func (*ListServicesRequest) ProtoMessage()    {}
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1c22ef5972cd4b, []int{18}
}

func (m *ListServicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServicesRequest.Unmarshal(m, b)
}
func (m *ListServicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServicesRequest.Marshal(b, m, deterministic)
}
func (m *ListServicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServicesRequest.Merge(m, src)
}
func (m *ListServicesRequest) XXX_Size() int {
	return xxx_messageInfo_ListServicesRequest.Size(m)
}
func (m *ListServicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListServicesRequest proto.InternalMessageInfo

type ListServicesResponse struct {
	Services             []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListServicesResponse) Reset()         { *m = ListServicesResponse{} }
func (m *ListServicesResponse) String() string { return proto.CompactTextString(m) }
func (*ListServicesResponse) ProtoMessage()    {}
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1c22ef5972cd4b, []int{19}
}

func (m *ListServicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServicesResponse.Unmarshal(m, b)
}
func (m *ListServicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServicesResponse.Marshal(b, m, deterministic)
}
func (m *ListServicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServicesResponse.Merge(m, src)
}
func (m *ListServicesResponse) XXX_Size() int {
	return xxx_messageInfo_ListServicesResponse.Size(m)
}
func (m *ListServicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListServicesResponse proto.InternalMessageInfo

func (m *ListServicesResponse) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type Service struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Source               string            `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Type                 string            `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1c22ef5972cd4b, []int{20}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Service) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Service) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Service) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterEnum("go.micro.service.platform.EventType", EventType_name, EventType_value)
	proto.RegisterType((*Status)(nil), "go.micro.service.platform.Status")
	proto.RegisterType((*StatusRequest)(nil), "go.micro.service.platform.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "go.micro.service.platform.StatusResponse")
	proto.RegisterMapType((map[string]*Status)(nil), "go.micro.service.platform.StatusResponse.RuntimeEntry")
	proto.RegisterType((*CreateEventRequest)(nil), "go.micro.service.platform.CreateEventRequest")
	proto.RegisterType((*CreateEventResponse)(nil), "go.micro.service.platform.CreateEventResponse")
	proto.RegisterType((*GetEventRequest)(nil), "go.micro.service.platform.GetEventRequest")
	proto.RegisterType((*GetEventResponse)(nil), "go.micro.service.platform.GetEventResponse")
	proto.RegisterType((*ListEventsRequest)(nil), "go.micro.service.platform.ListEventsRequest")
	proto.RegisterType((*ListEventsResponse)(nil), "go.micro.service.platform.ListEventsResponse")
	proto.RegisterType((*Event)(nil), "go.micro.service.platform.Event")
	proto.RegisterMapType((map[string]string)(nil), "go.micro.service.platform.Event.MetadataEntry")
	proto.RegisterType((*CreateServiceRequest)(nil), "go.micro.service.platform.CreateServiceRequest")
	proto.RegisterType((*CreateServiceResponse)(nil), "go.micro.service.platform.CreateServiceResponse")
	proto.RegisterType((*ReadServiceRequest)(nil), "go.micro.service.platform.ReadServiceRequest")
	proto.RegisterType((*ReadServiceResponse)(nil), "go.micro.service.platform.ReadServiceResponse")
	proto.RegisterType((*UpdateServiceRequest)(nil), "go.micro.service.platform.UpdateServiceRequest")
	proto.RegisterType((*UpdateServiceResponse)(nil), "go.micro.service.platform.UpdateServiceResponse")
	proto.RegisterType((*DeleteServiceRequest)(nil), "go.micro.service.platform.DeleteServiceRequest")
	proto.RegisterType((*DeleteServiceResponse)(nil), "go.micro.service.platform.DeleteServiceResponse")
	proto.RegisterType((*ListServicesRequest)(nil), "go.micro.service.platform.ListServicesRequest")
	proto.RegisterType((*ListServicesResponse)(nil), "go.micro.service.platform.ListServicesResponse")
	proto.RegisterType((*Service)(nil), "go.micro.service.platform.Service")
	proto.RegisterMapType((map[string]string)(nil), "go.micro.service.platform.Service.MetadataEntry")
}

func init() {
	proto.RegisterFile("github.com/micro/services/platform/service/proto/platform.proto", fileDescriptor_0f1c22ef5972cd4b)
}

var fileDescriptor_0f1c22ef5972cd4b = []byte{
	// 853 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0x5d, 0x53, 0xd3, 0x4c,
	0x14, 0xa6, 0xdf, 0xed, 0x29, 0x2d, 0xe1, 0x50, 0xde, 0xb7, 0x66, 0xbc, 0xc0, 0x8c, 0x17, 0x88,
	0x92, 0x32, 0x75, 0x06, 0xf1, 0x63, 0x74, 0x46, 0x05, 0x47, 0x06, 0x1d, 0x0c, 0xe0, 0x9d, 0xe3,
	0x84, 0x66, 0x81, 0x0c, 0x6d, 0x52, 0x92, 0x6d, 0x9d, 0xfe, 0x31, 0xff, 0x80, 0xff, 0xc7, 0x2b,
	0x2f, 0xbd, 0x70, 0xb2, 0x1f, 0x69, 0x52, 0x4a, 0x1a, 0xb5, 0xde, 0x65, 0x1f, 0xce, 0x79, 0x9e,
	0xdd, 0xb3, 0xcf, 0x9e, 0x53, 0xe0, 0xc5, 0xb9, 0x4d, 0x2f, 0x06, 0xa7, 0x7a, 0xc7, 0xed, 0xb5,
	0x7a, 0x76, 0xc7, 0x73, 0x5b, 0x3e, 0xf1, 0x86, 0x76, 0x87, 0xf8, 0xad, 0x7e, 0xd7, 0xa4, 0x67,
	0xae, 0xd7, 0x93, 0x48, 0xab, 0xef, 0xb9, 0xd4, 0x0d, 0x61, 0x9d, 0x2d, 0xf1, 0xd6, 0xb9, 0xab,
	0xb3, 0x44, 0x5d, 0x84, 0xe9, 0x32, 0x40, 0xdb, 0x83, 0xe2, 0x11, 0x35, 0xe9, 0xc0, 0x47, 0x84,
	0x7c, 0xc7, 0xb5, 0x48, 0x33, 0xb3, 0x96, 0x59, 0xaf, 0x18, 0xec, 0x3b, 0xc0, 0x6c, 0xe7, 0xcc,
	0x6d, 0x66, 0x39, 0x16, 0x7c, 0x63, 0x03, 0x0a, 0xc4, 0xf3, 0x5c, 0xaf, 0x99, 0x63, 0x20, 0x5f,
	0x68, 0x4b, 0x50, 0xe3, 0x3c, 0x06, 0xb9, 0x1a, 0x10, 0x9f, 0x6a, 0x3f, 0x33, 0x50, 0x97, 0x88,
	0xdf, 0x77, 0x1d, 0x9f, 0xe0, 0x63, 0x28, 0xfa, 0x0c, 0x61, 0x1a, 0xd5, 0xf6, 0x1d, 0xfd, 0xc6,
	0x7d, 0xe9, 0x22, 0x55, 0x24, 0xe0, 0x21, 0x94, 0xbc, 0x81, 0x43, 0xed, 0x1e, 0x69, 0x66, 0xd7,
	0x72, 0xeb, 0xd5, 0xf6, 0xf6, 0xec, 0x5c, 0x21, 0xab, 0x1b, 0x3c, 0x71, 0xd7, 0xa1, 0xde, 0xc8,
	0x90, 0x34, 0xea, 0x27, 0x58, 0x8c, 0xfe, 0x01, 0x15, 0xc8, 0x5d, 0x92, 0x91, 0x38, 0x7d, 0xf0,
	0x89, 0x8f, 0xa0, 0x30, 0x34, 0xbb, 0x03, 0xc2, 0x4e, 0x9f, 0x6a, 0xb7, 0x3c, 0xfe, 0x49, 0x76,
	0x27, 0xa3, 0x1d, 0x00, 0xbe, 0xf2, 0x88, 0x49, 0xc9, 0xee, 0x90, 0x38, 0x54, 0x14, 0x05, 0xb7,
	0xa1, 0x40, 0x82, 0xb5, 0x28, 0xc0, 0x5a, 0x02, 0x25, 0xcf, 0xe3, 0xe1, 0xda, 0x2a, 0xac, 0xc4,
	0xd8, 0xf8, 0xc9, 0xb4, 0xb7, 0xb0, 0xf4, 0x86, 0xd0, 0xb9, 0x28, 0xec, 0x83, 0x32, 0xa6, 0x12,
	0xf7, 0xf5, 0xa7, 0x5c, 0x1f, 0x60, 0xf9, 0xc0, 0xf6, 0x39, 0x99, 0xf4, 0x03, 0x3e, 0x83, 0x92,
	0xc8, 0x12, 0x74, 0x5a, 0x52, 0x3d, 0x39, 0x60, 0xc8, 0x14, 0xed, 0x3d, 0x60, 0x94, 0x52, 0x6c,
	0x70, 0x07, 0x8a, 0x4c, 0x31, 0x30, 0x54, 0x2e, 0xd5, 0x0e, 0x45, 0xbc, 0xf6, 0x35, 0x0b, 0x05,
	0x86, 0xe0, 0x0e, 0xe4, 0xe9, 0xa8, 0xcf, 0x37, 0x55, 0x6f, 0xdf, 0x9d, 0xc5, 0x70, 0x3c, 0xea,
	0x13, 0x83, 0x65, 0xe0, 0x6d, 0xa8, 0x04, 0xf6, 0xf1, 0xa9, 0xd9, 0xeb, 0x33, 0x8f, 0xe4, 0x8c,
	0x31, 0x80, 0xfb, 0x50, 0xee, 0x11, 0x6a, 0x5a, 0x26, 0x35, 0x9b, 0x39, 0xb6, 0x3b, 0x7d, 0x16,
	0xb7, 0xfe, 0x4e, 0x24, 0x70, 0xab, 0x86, 0xf9, 0xd1, 0xda, 0xe5, 0x7f, 0xbb, 0x76, 0x58, 0x87,
	0xac, 0x6d, 0x35, 0x0b, 0xcc, 0xd8, 0x59, 0xdb, 0x52, 0x9f, 0x42, 0x2d, 0x26, 0x34, 0xc5, 0xfa,
	0x8d, 0xa8, 0xf5, 0x2b, 0x51, 0x5f, 0x1f, 0x43, 0x83, 0x3b, 0x51, 0xca, 0xcc, 0xe5, 0x7a, 0xff,
	0x87, 0xd5, 0x09, 0x56, 0xe1, 0x70, 0x03, 0xd0, 0x20, 0xa6, 0x35, 0x57, 0xb1, 0x13, 0x58, 0x89,
	0x71, 0x0a, 0x33, 0x3d, 0x87, 0xb2, 0x6c, 0xab, 0xc2, 0x4e, 0x69, 0x58, 0xc3, 0x9c, 0xa0, 0x32,
	0x27, 0x7d, 0xeb, 0x1f, 0x54, 0x66, 0x82, 0x55, 0x54, 0xe6, 0x18, 0x1a, 0xaf, 0x49, 0x97, 0xcc,
	0x5f, 0x6e, 0x82, 0x55, 0xc8, 0xad, 0xc2, 0x4a, 0xf0, 0x00, 0x05, 0x1c, 0x76, 0xf9, 0x8f, 0xd0,
	0x88, 0xc3, 0x73, 0x2a, 0xe6, 0xf7, 0x0c, 0x94, 0x04, 0x1a, 0x0c, 0x21, 0xc7, 0xec, 0x85, 0x83,
	0x29, 0xf8, 0xc6, 0x26, 0x94, 0x86, 0xc4, 0xf3, 0x6d, 0xd7, 0x11, 0x16, 0x95, 0x4b, 0xfc, 0x0f,
	0x8a, 0xbe, 0x3b, 0xf0, 0x3a, 0x44, 0xcc, 0x27, 0xb1, 0x0a, 0x58, 0xd8, 0x3b, 0xcf, 0x73, 0x16,
	0xf6, 0x82, 0x0f, 0x22, 0x6f, 0xb4, 0xc0, 0x76, 0xb9, 0x35, 0x7b, 0x97, 0x37, 0xbd, 0xd2, 0xbf,
	0x7a, 0x57, 0x1b, 0xdf, 0x32, 0x50, 0x09, 0x1b, 0x0c, 0x56, 0xa1, 0x74, 0xe2, 0x5c, 0x3a, 0xee,
	0x17, 0x47, 0x59, 0x40, 0x84, 0xba, 0x90, 0xe6, 0x6f, 0xc4, 0x52, 0x32, 0x11, 0x8c, 0x5f, 0x97,
	0xa5, 0x64, 0x23, 0x18, 0x77, 0x8c, 0xa5, 0xe4, 0x50, 0x81, 0xc5, 0x97, 0x03, 0xbb, 0x6b, 0x1d,
	0x51, 0xd3, 0x0b, 0x90, 0x02, 0x2e, 0x43, 0x8d, 0x21, 0x7b, 0xb6, 0x63, 0xfb, 0x17, 0xc4, 0x52,
	0x8a, 0xb8, 0x04, 0x55, 0x0e, 0x99, 0x76, 0x97, 0x58, 0x4a, 0x29, 0x88, 0x39, 0x62, 0x55, 0x93,
	0x82, 0xf9, 0x31, 0x24, 0xb9, 0xcb, 0x63, 0x48, 0x6e, 0xa1, 0xd2, 0xfe, 0x51, 0x82, 0xf2, 0xa1,
	0xa8, 0x17, 0x7e, 0x0e, 0x7f, 0x5a, 0xac, 0xa7, 0x18, 0xd6, 0xcc, 0x4f, 0xea, 0xbd, 0xd4, 0x63,
	0x5d, 0x5b, 0x40, 0x07, 0xaa, 0x91, 0xa9, 0x88, 0x9b, 0x09, 0xb9, 0xd7, 0x67, 0xb1, 0xaa, 0xa7,
	0x0d, 0x0f, 0xf5, 0x2e, 0x01, 0xc6, 0x43, 0x08, 0x1f, 0x24, 0xe4, 0x5f, 0x1b, 0x7f, 0xea, 0x66,
	0xca, 0xe8, 0x50, 0x8c, 0x40, 0x59, 0x0e, 0x64, 0xdc, 0x48, 0x48, 0x9e, 0xf8, 0x01, 0xa0, 0xde,
	0x4f, 0x15, 0x1b, 0xca, 0x50, 0xa8, 0xc5, 0x3a, 0x2f, 0xb6, 0x66, 0x96, 0x25, 0xde, 0x70, 0xd4,
	0xad, 0xf4, 0x09, 0xd1, 0x9b, 0x8b, 0xb4, 0xe0, 0xc4, 0x9b, 0xbb, 0xde, 0xfe, 0x13, 0x6f, 0x6e,
	0x4a, 0x67, 0xe7, 0xa7, 0x8c, 0x75, 0xd1, 0xc4, 0x53, 0x4e, 0xeb, 0xe2, 0x89, 0xa7, 0x9c, 0xde,
	0xa0, 0x99, 0x6a, 0xac, 0x99, 0x26, 0xaa, 0x4e, 0x6b, 0xe6, 0x89, 0xaa, 0xd3, 0xfb, 0xf4, 0x02,
	0x5e, 0xc1, 0x62, 0xb4, 0x25, 0xa3, 0x3e, 0xc3, 0x79, 0x13, 0x2d, 0x5d, 0x6d, 0xa5, 0x8e, 0x97,
	0x92, 0xa7, 0x45, 0xf6, 0x6f, 0xc6, 0xc3, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x25, 0xb4,
	0xac, 0xa9, 0x0c, 0x00, 0x00,
}
