// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/micro/services/serverless/proto/serverless/serverless.proto

package go_micro_service_serverless

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type App struct {
	// eg. "my-app-1"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional commit hash to deploy a certain version
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// URL of the GitHub repo
	Source string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// One of the predefined image tags from here https://github.com/micro/cells
	// See top level folders
	Language string `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	// Optional folder to cd into while building the app.
	Folder               string   `protobuf:"bytes,5,opt,name=folder,proto3" json:"folder,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0f1dc5d38c37ce, []int{0}
}

func (m *App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App.Unmarshal(m, b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App.Marshal(b, m, deterministic)
}
func (m *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(m, src)
}
func (m *App) XXX_Size() int {
	return xxx_messageInfo_App.Size(m)
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *App) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *App) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *App) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *App) GetFolder() string {
	if m != nil {
		return m.Folder
	}
	return ""
}

type CreateRequest struct {
	App                  *App     `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0f1dc5d38c37ce, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

type CreateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0f1dc5d38c37ce, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

type DeleteRequest struct {
	App                  *App     `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0f1dc5d38c37ce, []int{3}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0f1dc5d38c37ce, []int{4}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0f1dc5d38c37ce, []int{5}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListResponse struct {
	Apps                 []*App   `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0f1dc5d38c37ce, []int{6}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetApps() []*App {
	if m != nil {
		return m.Apps
	}
	return nil
}

func init() {
	proto.RegisterType((*App)(nil), "go.micro.service.serverless.App")
	proto.RegisterType((*CreateRequest)(nil), "go.micro.service.serverless.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "go.micro.service.serverless.CreateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "go.micro.service.serverless.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "go.micro.service.serverless.DeleteResponse")
	proto.RegisterType((*ListRequest)(nil), "go.micro.service.serverless.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "go.micro.service.serverless.ListResponse")
}

func init() {
	proto.RegisterFile("github.com/micro/services/serverless/proto/serverless/serverless.proto", fileDescriptor_1e0f1dc5d38c37ce)
}

var fileDescriptor_1e0f1dc5d38c37ce = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0x05, 0xda, 0x8f, 0x4f, 0x07, 0x31, 0x66, 0x0e, 0x66, 0x83, 0x17, 0xd2, 0x13, 0x6a, 0xb2,
	0x24, 0xe8, 0x1f, 0x20, 0x10, 0x4f, 0x9e, 0xb8, 0x7b, 0x28, 0x75, 0xac, 0x4d, 0x4a, 0x77, 0xdc,
	0x69, 0xb9, 0xfa, 0x93, 0xfc, 0x8b, 0xa6, 0xdb, 0x56, 0xc0, 0x03, 0x34, 0xf1, 0x36, 0x6f, 0xe7,
	0xbd, 0x37, 0x33, 0x2f, 0x0b, 0x4f, 0x71, 0x92, 0xbf, 0x17, 0x6b, 0x1d, 0x99, 0xcd, 0x74, 0x93,
	0x44, 0xd6, 0x4c, 0x85, 0xec, 0x36, 0x89, 0x48, 0x5c, 0x41, 0x36, 0x25, 0x91, 0x29, 0x5b, 0x93,
	0x9b, 0xfd, 0x87, 0x5d, 0xa9, 0x5d, 0x0f, 0x6f, 0x62, 0xa3, 0x9d, 0x5e, 0xd7, 0x7a, 0xbd, 0xa3,
	0x04, 0x9f, 0xe0, 0xcd, 0x99, 0x11, 0xc1, 0xcf, 0xc2, 0x0d, 0xa9, 0xee, 0xb8, 0x3b, 0x39, 0x5f,
	0xb9, 0x1a, 0x15, 0xfc, 0xdf, 0x92, 0x95, 0xc4, 0x64, 0xaa, 0xe7, 0x9e, 0x1b, 0x88, 0xd7, 0xd0,
	0x17, 0x53, 0xd8, 0x88, 0x94, 0xe7, 0x1a, 0x35, 0xc2, 0x11, 0x9c, 0xa5, 0x61, 0x16, 0x17, 0x61,
	0x4c, 0xca, 0x77, 0x9d, 0x1f, 0x5c, 0x6a, 0xde, 0x4c, 0xfa, 0x4a, 0x56, 0xfd, 0xab, 0x34, 0x15,
	0x0a, 0x16, 0x30, 0x5c, 0x58, 0x0a, 0x73, 0x5a, 0xd1, 0x47, 0x41, 0x92, 0xe3, 0x0c, 0xbc, 0x90,
	0xd9, 0x6d, 0x32, 0x98, 0x8d, 0xf5, 0x91, 0xe5, 0xf5, 0x9c, 0x79, 0x55, 0x92, 0x83, 0x2b, 0xb8,
	0x6c, 0x4c, 0x84, 0x4d, 0x26, 0x54, 0xda, 0x2e, 0x29, 0xa5, 0x3f, 0xdb, 0x36, 0x26, 0xb5, 0xed,
	0x10, 0x06, 0xcf, 0x89, 0xe4, 0xb5, 0x69, 0xb0, 0x84, 0x8b, 0x0a, 0x56, 0x6d, 0x7c, 0x04, 0x3f,
	0x64, 0x16, 0xd5, 0x1d, 0x7b, 0xad, 0xa6, 0x38, 0xf6, 0xec, 0xab, 0x07, 0xfe, 0x9c, 0x59, 0x30,
	0x82, 0x7e, 0x75, 0x06, 0xde, 0x1d, 0x95, 0x1e, 0x04, 0x36, 0xba, 0x6f, 0xc5, 0xad, 0x0f, 0xe8,
	0x94, 0x43, 0xaa, 0xa3, 0x4e, 0x0c, 0x39, 0x88, 0xef, 0xc4, 0x90, 0x5f, 0x29, 0x75, 0xf0, 0x05,
	0xfc, 0x32, 0x18, 0x9c, 0x1c, 0x95, 0xed, 0x45, 0x39, 0xba, 0x6d, 0xc1, 0x6c, 0xec, 0xd7, 0x7d,
	0xf7, 0xb3, 0x1f, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x44, 0xf6, 0xf9, 0x8b, 0x23, 0x03, 0x00,
	0x00,
}
