// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/micro/services/subscribe/proto/subscribe/subscribe.proto

package go_micro_srv_subscribe

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubscribeRequest struct {
	// namespaces are owned by the account that first creates a subscription in them
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_840b6ad5b6875c39, []int{0}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *SubscribeRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type SubscribeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeResponse) Reset()         { *m = SubscribeResponse{} }
func (m *SubscribeResponse) String() string { return proto.CompactTextString(m) }
func (*SubscribeResponse) ProtoMessage()    {}
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_840b6ad5b6875c39, []int{1}
}

func (m *SubscribeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeResponse.Unmarshal(m, b)
}
func (m *SubscribeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeResponse.Marshal(b, m, deterministic)
}
func (m *SubscribeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeResponse.Merge(m, src)
}
func (m *SubscribeResponse) XXX_Size() int {
	return xxx_messageInfo_SubscribeResponse.Size(m)
}
func (m *SubscribeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeResponse proto.InternalMessageInfo

type ListSubscriptionsRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSubscriptionsRequest) Reset()         { *m = ListSubscriptionsRequest{} }
func (m *ListSubscriptionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListSubscriptionsRequest) ProtoMessage()    {}
func (*ListSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_840b6ad5b6875c39, []int{2}
}

func (m *ListSubscriptionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSubscriptionsRequest.Unmarshal(m, b)
}
func (m *ListSubscriptionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSubscriptionsRequest.Marshal(b, m, deterministic)
}
func (m *ListSubscriptionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSubscriptionsRequest.Merge(m, src)
}
func (m *ListSubscriptionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListSubscriptionsRequest.Size(m)
}
func (m *ListSubscriptionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSubscriptionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSubscriptionsRequest proto.InternalMessageInfo

func (m *ListSubscriptionsRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type ListSubscriptionsResponse struct {
	Subscriptions        []*Subscription `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListSubscriptionsResponse) Reset()         { *m = ListSubscriptionsResponse{} }
func (m *ListSubscriptionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListSubscriptionsResponse) ProtoMessage()    {}
func (*ListSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_840b6ad5b6875c39, []int{3}
}

func (m *ListSubscriptionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSubscriptionsResponse.Unmarshal(m, b)
}
func (m *ListSubscriptionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSubscriptionsResponse.Marshal(b, m, deterministic)
}
func (m *ListSubscriptionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSubscriptionsResponse.Merge(m, src)
}
func (m *ListSubscriptionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListSubscriptionsResponse.Size(m)
}
func (m *ListSubscriptionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSubscriptionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSubscriptionsResponse proto.InternalMessageInfo

func (m *ListSubscriptionsResponse) GetSubscriptions() []*Subscription {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

type Subscription struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subscription) Reset()         { *m = Subscription{} }
func (m *Subscription) String() string { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()    {}
func (*Subscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_840b6ad5b6875c39, []int{4}
}

func (m *Subscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscription.Unmarshal(m, b)
}
func (m *Subscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscription.Marshal(b, m, deterministic)
}
func (m *Subscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscription.Merge(m, src)
}
func (m *Subscription) XXX_Size() int {
	return xxx_messageInfo_Subscription.Size(m)
}
func (m *Subscription) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscription.DiscardUnknown(m)
}

var xxx_messageInfo_Subscription proto.InternalMessageInfo

func (m *Subscription) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*SubscribeRequest)(nil), "go.micro.service.subscribe.SubscribeRequest")
	proto.RegisterType((*SubscribeResponse)(nil), "go.micro.service.subscribe.SubscribeResponse")
	proto.RegisterType((*ListSubscriptionsRequest)(nil), "go.micro.service.subscribe.ListSubscriptionsRequest")
	proto.RegisterType((*ListSubscriptionsResponse)(nil), "go.micro.service.subscribe.ListSubscriptionsResponse")
	proto.RegisterType((*Subscription)(nil), "go.micro.service.subscribe.Subscription")
}

func init() {
	proto.RegisterFile("github.com/micro/services/subscribe/proto/subscribe/subscribe.proto", fileDescriptor_840b6ad5b6875c39)
}

var fileDescriptor_840b6ad5b6875c39 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xc1, 0x4a, 0x03, 0x31,
	0x14, 0x34, 0x8a, 0xc2, 0x3e, 0x15, 0x6c, 0x14, 0x59, 0x8b, 0x87, 0x12, 0x7a, 0x58, 0x2f, 0x59,
	0xad, 0x17, 0xef, 0x82, 0x07, 0xf1, 0xb4, 0x7e, 0xc1, 0x26, 0x3c, 0xd6, 0x80, 0xbb, 0x59, 0xf3,
	0xb2, 0x3d, 0xf8, 0xcb, 0xfe, 0x84, 0x90, 0xb6, 0x69, 0xc4, 0x16, 0xeb, 0x2d, 0x93, 0xc9, 0xcc,
	0x30, 0x43, 0xe0, 0xb1, 0x31, 0xfe, 0x6d, 0x50, 0x52, 0xdb, 0xb6, 0x6c, 0x8d, 0x76, 0xb6, 0x24,
	0x74, 0x73, 0xa3, 0x91, 0x4a, 0x1a, 0x14, 0x69, 0x67, 0x14, 0x96, 0xbd, 0xb3, 0xde, 0x26, 0x38,
	0x9e, 0x64, 0x60, 0xf8, 0x65, 0x63, 0x65, 0x10, 0x4b, 0x72, 0x73, 0x19, 0x59, 0xf1, 0x04, 0x67,
	0xaf, 0x2b, 0x50, 0xe1, 0xc7, 0x80, 0xe4, 0xf9, 0x35, 0x64, 0x5d, 0xdd, 0x22, 0xf5, 0xb5, 0xc6,
	0x9c, 0x4d, 0x58, 0x91, 0x55, 0xeb, 0x0b, 0x7e, 0x01, 0x87, 0xd8, 0xd6, 0xe6, 0x3d, 0xdf, 0x0f,
	0xcc, 0x02, 0x88, 0x73, 0x18, 0x25, 0x3e, 0xd4, 0xdb, 0x8e, 0x50, 0x3c, 0x40, 0xfe, 0x62, 0xc8,
	0x2f, 0x89, 0xde, 0x1b, 0xdb, 0xd1, 0x4e, 0x21, 0xa2, 0x81, 0xab, 0x0d, 0xca, 0x85, 0x2d, 0x7f,
	0x86, 0x53, 0x4a, 0x89, 0x9c, 0x4d, 0x0e, 0x8a, 0xe3, 0xd9, 0x54, 0x6e, 0xee, 0x28, 0x53, 0x97,
	0xea, 0xa7, 0x54, 0x4c, 0xe1, 0x24, 0xa5, 0xd7, 0xed, 0x58, 0xd2, 0x6e, 0xf6, 0xc5, 0x20, 0x8b,
	0xf5, 0xb8, 0x4a, 0x41, 0xf1, 0x47, 0x6a, 0x9c, 0x75, 0x7c, 0xb3, 0xc3, 0xcb, 0xe5, 0x70, 0x7b,
	0xfc, 0x13, 0x46, 0xbf, 0x06, 0xe0, 0xb7, 0xdb, 0x1c, 0xb6, 0xad, 0x3c, 0xbe, 0xfb, 0x87, 0x62,
	0x95, 0xad, 0x8e, 0xc2, 0x97, 0xb9, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x9f, 0x31, 0x6b,
	0x79, 0x02, 0x00, 0x00,
}
