// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/micro/services/account/api/proto/account/account.proto

package go_micro_api_account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignupRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	InviteCode           string   `protobuf:"bytes,3,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	ProjectInvite        bool     `protobuf:"varint,4,opt,name=project_invite,json=projectInvite,proto3" json:"project_invite,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupRequest) Reset()         { *m = SignupRequest{} }
func (m *SignupRequest) String() string { return proto.CompactTextString(m) }
func (*SignupRequest) ProtoMessage()    {}
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc07e0df5059f8a7, []int{0}
}

func (m *SignupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupRequest.Unmarshal(m, b)
}
func (m *SignupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupRequest.Marshal(b, m, deterministic)
}
func (m *SignupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupRequest.Merge(m, src)
}
func (m *SignupRequest) XXX_Size() int {
	return xxx_messageInfo_SignupRequest.Size(m)
}
func (m *SignupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignupRequest proto.InternalMessageInfo

func (m *SignupRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignupRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignupRequest) GetInviteCode() string {
	if m != nil {
		return m.InviteCode
	}
	return ""
}

func (m *SignupRequest) GetProjectInvite() bool {
	if m != nil {
		return m.ProjectInvite
	}
	return false
}

type SignupResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Token                *Token   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupResponse) Reset()         { *m = SignupResponse{} }
func (m *SignupResponse) String() string { return proto.CompactTextString(m) }
func (*SignupResponse) ProtoMessage()    {}
func (*SignupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc07e0df5059f8a7, []int{1}
}

func (m *SignupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupResponse.Unmarshal(m, b)
}
func (m *SignupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupResponse.Marshal(b, m, deterministic)
}
func (m *SignupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupResponse.Merge(m, src)
}
func (m *SignupResponse) XXX_Size() int {
	return xxx_messageInfo_SignupResponse.Size(m)
}
func (m *SignupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignupResponse proto.InternalMessageInfo

func (m *SignupResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *SignupResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *SignupResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc07e0df5059f8a7, []int{2}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Token                *Token   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc07e0df5059f8a7, []int{3}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LoginResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *LoginResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type Plan struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Amount               int64    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Interval             string   `protobuf:"bytes,4,opt,name=interval,proto3" json:"interval,omitempty"`
	Available            bool     `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Plan) Reset()         { *m = Plan{} }
func (m *Plan) String() string { return proto.CompactTextString(m) }
func (*Plan) ProtoMessage()    {}
func (*Plan) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc07e0df5059f8a7, []int{4}
}

func (m *Plan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plan.Unmarshal(m, b)
}
func (m *Plan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plan.Marshal(b, m, deterministic)
}
func (m *Plan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plan.Merge(m, src)
}
func (m *Plan) XXX_Size() int {
	return xxx_messageInfo_Plan.Size(m)
}
func (m *Plan) XXX_DiscardUnknown() {
	xxx_messageInfo_Plan.DiscardUnknown(m)
}

var xxx_messageInfo_Plan proto.InternalMessageInfo

func (m *Plan) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Plan) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Plan) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Plan) GetInterval() string {
	if m != nil {
		return m.Interval
	}
	return ""
}

func (m *Plan) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

type Subscription struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Plan                 *Plan    `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subscription) Reset()         { *m = Subscription{} }
func (m *Subscription) String() string { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()    {}
func (*Subscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc07e0df5059f8a7, []int{5}
}

func (m *Subscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscription.Unmarshal(m, b)
}
func (m *Subscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscription.Marshal(b, m, deterministic)
}
func (m *Subscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscription.Merge(m, src)
}
func (m *Subscription) XXX_Size() int {
	return xxx_messageInfo_Subscription.Size(m)
}
func (m *Subscription) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscription.DiscardUnknown(m)
}

var xxx_messageInfo_Subscription proto.InternalMessageInfo

func (m *Subscription) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Subscription) GetPlan() *Plan {
	if m != nil {
		return m.Plan
	}
	return nil
}

type Token struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Created              int64    `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Expiry               int64    `protobuf:"varint,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc07e0df5059f8a7, []int{6}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *Token) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *Token) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Token) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,3,opt,name=updated,proto3" json:"updated,omitempty"`
	FirstName            string   `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Scopes               []string `protobuf:"bytes,7,rep,name=scopes,proto3" json:"scopes,omitempty"`
	InviteCode           string   `protobuf:"bytes,8,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	InviteVerified       bool     `protobuf:"varint,9,opt,name=invite_verified,json=inviteVerified,proto3" json:"invite_verified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc07e0df5059f8a7, []int{7}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *User) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

func (m *User) GetInviteCode() string {
	if m != nil {
		return m.InviteCode
	}
	return ""
}

func (m *User) GetInviteVerified() bool {
	if m != nil {
		return m.InviteVerified
	}
	return false
}

type ReadUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserRequest) Reset()         { *m = ReadUserRequest{} }
func (m *ReadUserRequest) String() string { return proto.CompactTextString(m) }
func (*ReadUserRequest) ProtoMessage()    {}
func (*ReadUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc07e0df5059f8a7, []int{8}
}

func (m *ReadUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserRequest.Unmarshal(m, b)
}
func (m *ReadUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserRequest.Marshal(b, m, deterministic)
}
func (m *ReadUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserRequest.Merge(m, src)
}
func (m *ReadUserRequest) XXX_Size() int {
	return xxx_messageInfo_ReadUserRequest.Size(m)
}
func (m *ReadUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserRequest proto.InternalMessageInfo

type ReadUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserResponse) Reset()         { *m = ReadUserResponse{} }
func (m *ReadUserResponse) String() string { return proto.CompactTextString(m) }
func (*ReadUserResponse) ProtoMessage()    {}
func (*ReadUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc07e0df5059f8a7, []int{9}
}

func (m *ReadUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserResponse.Unmarshal(m, b)
}
func (m *ReadUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserResponse.Marshal(b, m, deterministic)
}
func (m *ReadUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserResponse.Merge(m, src)
}
func (m *ReadUserResponse) XXX_Size() int {
	return xxx_messageInfo_ReadUserResponse.Size(m)
}
func (m *ReadUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserResponse proto.InternalMessageInfo

func (m *ReadUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc07e0df5059f8a7, []int{10}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc07e0df5059f8a7, []int{11}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc07e0df5059f8a7, []int{12}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

type DeleteUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc07e0df5059f8a7, []int{13}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

type TokenRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenRequest) Reset()         { *m = TokenRequest{} }
func (m *TokenRequest) String() string { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()    {}
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc07e0df5059f8a7, []int{14}
}

func (m *TokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenRequest.Unmarshal(m, b)
}
func (m *TokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenRequest.Marshal(b, m, deterministic)
}
func (m *TokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenRequest.Merge(m, src)
}
func (m *TokenRequest) XXX_Size() int {
	return xxx_messageInfo_TokenRequest.Size(m)
}
func (m *TokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenRequest proto.InternalMessageInfo

func (m *TokenRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TokenRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type TokenResponse struct {
	Token                *Token   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenResponse) Reset()         { *m = TokenResponse{} }
func (m *TokenResponse) String() string { return proto.CompactTextString(m) }
func (*TokenResponse) ProtoMessage()    {}
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc07e0df5059f8a7, []int{15}
}

func (m *TokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenResponse.Unmarshal(m, b)
}
func (m *TokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenResponse.Marshal(b, m, deterministic)
}
func (m *TokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenResponse.Merge(m, src)
}
func (m *TokenResponse) XXX_Size() int {
	return xxx_messageInfo_TokenResponse.Size(m)
}
func (m *TokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenResponse proto.InternalMessageInfo

func (m *TokenResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func init() {
	proto.RegisterType((*SignupRequest)(nil), "go.micro.api.account.SignupRequest")
	proto.RegisterType((*SignupResponse)(nil), "go.micro.api.account.SignupResponse")
	proto.RegisterType((*LoginRequest)(nil), "go.micro.api.account.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "go.micro.api.account.LoginResponse")
	proto.RegisterType((*Plan)(nil), "go.micro.api.account.Plan")
	proto.RegisterType((*Subscription)(nil), "go.micro.api.account.Subscription")
	proto.RegisterType((*Token)(nil), "go.micro.api.account.Token")
	proto.RegisterType((*User)(nil), "go.micro.api.account.User")
	proto.RegisterType((*ReadUserRequest)(nil), "go.micro.api.account.ReadUserRequest")
	proto.RegisterType((*ReadUserResponse)(nil), "go.micro.api.account.ReadUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "go.micro.api.account.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "go.micro.api.account.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "go.micro.api.account.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "go.micro.api.account.DeleteUserResponse")
	proto.RegisterType((*TokenRequest)(nil), "go.micro.api.account.TokenRequest")
	proto.RegisterType((*TokenResponse)(nil), "go.micro.api.account.TokenResponse")
}

func init() {
	proto.RegisterFile("github.com/micro/services/account/api/proto/account/account.proto", fileDescriptor_fc07e0df5059f8a7)
}

var fileDescriptor_fc07e0df5059f8a7 = []byte{
	// 714 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0xae, 0x13, 0xe7, 0xc3, 0xd3, 0x24, 0x7d, 0xbb, 0x6f, 0x55, 0x59, 0xe9, 0xfb, 0x8a, 0xb2,
	0xa5, 0x34, 0x27, 0x47, 0x94, 0x3f, 0x40, 0x3f, 0x2e, 0x48, 0xa8, 0xaa, 0x5c, 0xca, 0x85, 0x43,
	0xb4, 0xb1, 0xb7, 0xe9, 0x82, 0xe3, 0x35, 0xbb, 0x76, 0x00, 0x89, 0x0b, 0x47, 0x7e, 0x01, 0xfc,
	0x01, 0xfe, 0x26, 0x42, 0xde, 0xdd, 0x24, 0xce, 0x67, 0x4b, 0x4f, 0x9c, 0x92, 0x79, 0x66, 0xf6,
	0xd9, 0x99, 0x79, 0x66, 0xb2, 0x81, 0x93, 0x01, 0x4b, 0x6f, 0xb3, 0xbe, 0x17, 0xf0, 0x61, 0x77,
	0xc8, 0x02, 0xc1, 0xbb, 0x92, 0x8a, 0x11, 0x0b, 0xa8, 0xec, 0x92, 0x20, 0xe0, 0x59, 0x9c, 0x76,
	0x49, 0xc2, 0xba, 0x89, 0xe0, 0x29, 0x9f, 0x22, 0xfa, 0xd3, 0x53, 0x28, 0xda, 0x19, 0x70, 0x4f,
	0x1d, 0xf5, 0x48, 0xc2, 0x3c, 0xe3, 0xc3, 0xdf, 0x2c, 0x68, 0x5e, 0xb1, 0x41, 0x9c, 0x25, 0x3e,
	0xfd, 0x90, 0x51, 0x99, 0xa2, 0x1d, 0xa8, 0xd0, 0x21, 0x61, 0x91, 0x6b, 0xed, 0x5b, 0x1d, 0xc7,
	0xd7, 0x06, 0x6a, 0x43, 0x3d, 0x21, 0x52, 0x7e, 0xe4, 0x22, 0x74, 0x4b, 0xca, 0x31, 0xb1, 0xd1,
	0x23, 0xd8, 0x64, 0xf1, 0x88, 0xa5, 0xb4, 0x17, 0xf0, 0x90, 0xba, 0x65, 0xe5, 0x06, 0x0d, 0x9d,
	0xf1, 0x90, 0xa2, 0x43, 0x68, 0x25, 0x82, 0xbf, 0xa3, 0x41, 0xda, 0xd3, 0xa8, 0x6b, 0xef, 0x5b,
	0x9d, 0xba, 0xdf, 0x34, 0xe8, 0x4b, 0x05, 0xe2, 0x1f, 0x16, 0xb4, 0xc6, 0xb9, 0xc8, 0x84, 0xc7,
	0x92, 0x22, 0x0f, 0xec, 0x4c, 0x52, 0xa1, 0x72, 0xd9, 0x3c, 0x6e, 0x7b, 0xcb, 0x6a, 0xf0, 0xae,
	0x25, 0x15, 0xbe, 0x8a, 0x43, 0x07, 0xd0, 0x14, 0xf4, 0x46, 0x50, 0x79, 0xdb, 0x4b, 0xf9, 0x7b,
	0x1a, 0x9b, 0x5c, 0x1b, 0x06, 0x7c, 0x9d, 0x63, 0xe8, 0x19, 0x54, 0xb4, 0xb3, 0xac, 0x58, 0xf7,
	0x96, 0xb3, 0xaa, 0x58, 0x5f, 0x47, 0xe2, 0x17, 0xd0, 0x78, 0xc5, 0x07, 0x2c, 0x7e, 0x70, 0x93,
	0xf0, 0x77, 0x0b, 0x9a, 0x86, 0xe2, 0x2f, 0xab, 0xed, 0x0b, 0xd8, 0x97, 0x11, 0x89, 0x51, 0x0b,
	0x4a, 0x2c, 0x34, 0x05, 0x95, 0x58, 0x88, 0x10, 0xd8, 0x31, 0x19, 0x52, 0x73, 0x8d, 0xfa, 0x8e,
	0x76, 0xa1, 0x4a, 0x86, 0x39, 0x85, 0xe2, 0x2f, 0xfb, 0xc6, 0xca, 0x2b, 0x67, 0x71, 0x4a, 0xc5,
	0x88, 0x44, 0x4a, 0x5b, 0xc7, 0x9f, 0xd8, 0xe8, 0x3f, 0x70, 0xc8, 0x88, 0xb0, 0x88, 0xf4, 0x23,
	0xea, 0x56, 0x94, 0xf0, 0x53, 0x00, 0x5f, 0x40, 0xe3, 0x2a, 0xeb, 0xcb, 0x40, 0xb0, 0x24, 0x65,
	0x7c, 0x31, 0x0b, 0x0f, 0xec, 0x24, 0x22, 0xba, 0xd8, 0x95, 0x5d, 0xca, 0xf3, 0xf7, 0x55, 0x1c,
	0xfe, 0x6a, 0x41, 0x45, 0xb7, 0xe2, 0x31, 0x34, 0x48, 0x10, 0x50, 0x29, 0x4d, 0xbb, 0x34, 0xe7,
	0xa6, 0xc6, 0x74, 0xc8, 0xbd, 0x5a, 0xea, 0x42, 0x2d, 0x10, 0x94, 0xa4, 0x34, 0x34, 0x45, 0x8f,
	0xcd, 0xbc, 0x1b, 0xf4, 0x53, 0xc2, 0xc4, 0x67, 0x55, 0x73, 0xd9, 0x37, 0x16, 0xfe, 0x65, 0x81,
	0x9d, 0x0b, 0xb7, 0x50, 0x4c, 0x81, 0xaa, 0x34, 0x4b, 0xe5, 0x42, 0x2d, 0x4b, 0xc2, 0xe2, 0x25,
	0xc6, 0x44, 0xff, 0x03, 0xdc, 0x30, 0x21, 0xd3, 0x9e, 0x12, 0x43, 0x37, 0xd7, 0x51, 0xc8, 0x45,
	0xae, 0xc8, 0x1e, 0x38, 0x11, 0x19, 0x7b, 0x2b, 0xba, 0xf5, 0x39, 0xa0, 0x9c, 0x93, 0x31, 0xad,
	0x16, 0xc7, 0x74, 0x17, 0xaa, 0x32, 0xe0, 0x09, 0x95, 0x6e, 0x6d, 0xbf, 0xdc, 0x71, 0x7c, 0x63,
	0xcd, 0xef, 0x71, 0x7d, 0x61, 0x8f, 0x8f, 0x60, 0xcb, 0x04, 0x8c, 0xa8, 0x60, 0x37, 0x8c, 0x86,
	0xae, 0xa3, 0xf4, 0x6c, 0x69, 0xf8, 0x8d, 0x41, 0xf1, 0x36, 0x6c, 0xf9, 0x94, 0x84, 0x6a, 0x78,
	0xf5, 0xc6, 0xe0, 0x53, 0xf8, 0x67, 0x0a, 0x3d, 0x6c, 0x03, 0xf0, 0x19, 0x6c, 0x5f, 0xab, 0xae,
	0x14, 0x88, 0xff, 0x98, 0xe4, 0x1c, 0x50, 0x91, 0xe4, 0x81, 0xa9, 0xfc, 0x0b, 0xdb, 0xe7, 0x34,
	0xa2, 0x33, 0xa9, 0xe0, 0x1d, 0x40, 0x45, 0x50, 0x53, 0xe3, 0x33, 0x68, 0xe8, 0x7d, 0x33, 0x09,
	0xcf, 0x0f, 0xc5, 0x7d, 0x86, 0x10, 0x9f, 0x42, 0xd3, 0x90, 0x98, 0x84, 0x27, 0x8b, 0x6e, 0xdd,
	0x77, 0xd1, 0x8f, 0x7f, 0xda, 0x50, 0x3b, 0xd1, 0x0e, 0xf4, 0x16, 0xea, 0x63, 0x39, 0xd0, 0xe1,
	0xf2, 0xb3, 0x73, 0x0a, 0xb6, 0x9f, 0xde, 0x15, 0x66, 0xea, 0xdd, 0x40, 0x04, 0x60, 0xda, 0x62,
	0x74, 0xb4, 0xa2, 0x99, 0xf3, 0x4a, 0xb6, 0x3b, 0x77, 0x07, 0x16, 0xaf, 0x98, 0xb6, 0x7a, 0xd5,
	0x15, 0x0b, 0x0a, 0xad, 0xba, 0x62, 0x89, 0x6a, 0x1b, 0xe8, 0x0a, 0xaa, 0xfa, 0x35, 0x42, 0x07,
	0xcb, 0x4f, 0xcd, 0xbc, 0x9b, 0xed, 0x27, 0xeb, 0x83, 0x8c, 0x6c, 0x97, 0x50, 0x51, 0xaf, 0x00,
	0xc2, 0xcb, 0xc3, 0x8b, 0xaf, 0x4c, 0xfb, 0x60, 0x6d, 0xcc, 0x94, 0x51, 0xff, 0x4e, 0xe1, 0x75,
	0x23, 0xb0, 0x9e, 0x71, 0x66, 0xb4, 0xfa, 0x55, 0xf5, 0x87, 0xe1, 0xf9, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x09, 0xc9, 0x90, 0x50, 0x75, 0x08, 0x00, 0x00,
}
