// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/api.proto

package go_micro_api_platform

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReadUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserRequest) Reset()         { *m = ReadUserRequest{} }
func (m *ReadUserRequest) String() string { return proto.CompactTextString(m) }
func (*ReadUserRequest) ProtoMessage()    {}
func (*ReadUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{0}
}

func (m *ReadUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserRequest.Unmarshal(m, b)
}
func (m *ReadUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserRequest.Marshal(b, m, deterministic)
}
func (m *ReadUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserRequest.Merge(m, src)
}
func (m *ReadUserRequest) XXX_Size() int {
	return xxx_messageInfo_ReadUserRequest.Size(m)
}
func (m *ReadUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserRequest proto.InternalMessageInfo

type ReadUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserResponse) Reset()         { *m = ReadUserResponse{} }
func (m *ReadUserResponse) String() string { return proto.CompactTextString(m) }
func (*ReadUserResponse) ProtoMessage()    {}
func (*ReadUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{1}
}

func (m *ReadUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserResponse.Unmarshal(m, b)
}
func (m *ReadUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserResponse.Marshal(b, m, deterministic)
}
func (m *ReadUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserResponse.Merge(m, src)
}
func (m *ReadUserResponse) XXX_Size() int {
	return xxx_messageInfo_ReadUserResponse.Size(m)
}
func (m *ReadUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserResponse proto.InternalMessageInfo

func (m *ReadUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateServiceRequest struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateServiceRequest) Reset()         { *m = CreateServiceRequest{} }
func (m *CreateServiceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateServiceRequest) ProtoMessage()    {}
func (*CreateServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{2}
}

func (m *CreateServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateServiceRequest.Unmarshal(m, b)
}
func (m *CreateServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateServiceRequest.Marshal(b, m, deterministic)
}
func (m *CreateServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateServiceRequest.Merge(m, src)
}
func (m *CreateServiceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateServiceRequest.Size(m)
}
func (m *CreateServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateServiceRequest proto.InternalMessageInfo

func (m *CreateServiceRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type CreateServiceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateServiceResponse) Reset()         { *m = CreateServiceResponse{} }
func (m *CreateServiceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateServiceResponse) ProtoMessage()    {}
func (*CreateServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{3}
}

func (m *CreateServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateServiceResponse.Unmarshal(m, b)
}
func (m *CreateServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateServiceResponse.Marshal(b, m, deterministic)
}
func (m *CreateServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateServiceResponse.Merge(m, src)
}
func (m *CreateServiceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateServiceResponse.Size(m)
}
func (m *CreateServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateServiceResponse proto.InternalMessageInfo

type ReadServiceRequest struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadServiceRequest) Reset()         { *m = ReadServiceRequest{} }
func (m *ReadServiceRequest) String() string { return proto.CompactTextString(m) }
func (*ReadServiceRequest) ProtoMessage()    {}
func (*ReadServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{4}
}

func (m *ReadServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadServiceRequest.Unmarshal(m, b)
}
func (m *ReadServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadServiceRequest.Marshal(b, m, deterministic)
}
func (m *ReadServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadServiceRequest.Merge(m, src)
}
func (m *ReadServiceRequest) XXX_Size() int {
	return xxx_messageInfo_ReadServiceRequest.Size(m)
}
func (m *ReadServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadServiceRequest proto.InternalMessageInfo

func (m *ReadServiceRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type ReadServiceResponse struct {
	Services             []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReadServiceResponse) Reset()         { *m = ReadServiceResponse{} }
func (m *ReadServiceResponse) String() string { return proto.CompactTextString(m) }
func (*ReadServiceResponse) ProtoMessage()    {}
func (*ReadServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{5}
}

func (m *ReadServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadServiceResponse.Unmarshal(m, b)
}
func (m *ReadServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadServiceResponse.Marshal(b, m, deterministic)
}
func (m *ReadServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadServiceResponse.Merge(m, src)
}
func (m *ReadServiceResponse) XXX_Size() int {
	return xxx_messageInfo_ReadServiceResponse.Size(m)
}
func (m *ReadServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadServiceResponse proto.InternalMessageInfo

func (m *ReadServiceResponse) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type UpdateServiceRequest struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateServiceRequest) Reset()         { *m = UpdateServiceRequest{} }
func (m *UpdateServiceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateServiceRequest) ProtoMessage()    {}
func (*UpdateServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{6}
}

func (m *UpdateServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateServiceRequest.Unmarshal(m, b)
}
func (m *UpdateServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateServiceRequest.Marshal(b, m, deterministic)
}
func (m *UpdateServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateServiceRequest.Merge(m, src)
}
func (m *UpdateServiceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateServiceRequest.Size(m)
}
func (m *UpdateServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateServiceRequest proto.InternalMessageInfo

func (m *UpdateServiceRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type UpdateServiceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateServiceResponse) Reset()         { *m = UpdateServiceResponse{} }
func (m *UpdateServiceResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateServiceResponse) ProtoMessage()    {}
func (*UpdateServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{7}
}

func (m *UpdateServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateServiceResponse.Unmarshal(m, b)
}
func (m *UpdateServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateServiceResponse.Marshal(b, m, deterministic)
}
func (m *UpdateServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateServiceResponse.Merge(m, src)
}
func (m *UpdateServiceResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateServiceResponse.Size(m)
}
func (m *UpdateServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateServiceResponse proto.InternalMessageInfo

type DeleteServiceRequest struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteServiceRequest) Reset()         { *m = DeleteServiceRequest{} }
func (m *DeleteServiceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteServiceRequest) ProtoMessage()    {}
func (*DeleteServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{8}
}

func (m *DeleteServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteServiceRequest.Unmarshal(m, b)
}
func (m *DeleteServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteServiceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteServiceRequest.Merge(m, src)
}
func (m *DeleteServiceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteServiceRequest.Size(m)
}
func (m *DeleteServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteServiceRequest proto.InternalMessageInfo

func (m *DeleteServiceRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type DeleteServiceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteServiceResponse) Reset()         { *m = DeleteServiceResponse{} }
func (m *DeleteServiceResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteServiceResponse) ProtoMessage()    {}
func (*DeleteServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{9}
}

func (m *DeleteServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteServiceResponse.Unmarshal(m, b)
}
func (m *DeleteServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteServiceResponse.Marshal(b, m, deterministic)
}
func (m *DeleteServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteServiceResponse.Merge(m, src)
}
func (m *DeleteServiceResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteServiceResponse.Size(m)
}
func (m *DeleteServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteServiceResponse proto.InternalMessageInfo

type ListServicesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListServicesRequest) Reset()         { *m = ListServicesRequest{} }
func (m *ListServicesRequest) String() string { return proto.CompactTextString(m) }
func (*ListServicesRequest) ProtoMessage()    {}
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{10}
}

func (m *ListServicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServicesRequest.Unmarshal(m, b)
}
func (m *ListServicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServicesRequest.Marshal(b, m, deterministic)
}
func (m *ListServicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServicesRequest.Merge(m, src)
}
func (m *ListServicesRequest) XXX_Size() int {
	return xxx_messageInfo_ListServicesRequest.Size(m)
}
func (m *ListServicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListServicesRequest proto.InternalMessageInfo

type ListServicesResponse struct {
	Services             []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListServicesResponse) Reset()         { *m = ListServicesResponse{} }
func (m *ListServicesResponse) String() string { return proto.CompactTextString(m) }
func (*ListServicesResponse) ProtoMessage()    {}
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{11}
}

func (m *ListServicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServicesResponse.Unmarshal(m, b)
}
func (m *ListServicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServicesResponse.Marshal(b, m, deterministic)
}
func (m *ListServicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServicesResponse.Merge(m, src)
}
func (m *ListServicesResponse) XXX_Size() int {
	return xxx_messageInfo_ListServicesResponse.Size(m)
}
func (m *ListServicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListServicesResponse proto.InternalMessageInfo

func (m *ListServicesResponse) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type Service struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Source               string            `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Type                 string            `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{12}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Service) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Service) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Service) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type User struct {
	Name                  string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                 string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Login                 string   `protobuf:"bytes,3,opt,name=login,proto3" json:"login,omitempty"`
	AvatarUrl             string   `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	TeamName              string   `protobuf:"bytes,5,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	TeamUrl               string   `protobuf:"bytes,6,opt,name=team_url,json=teamUrl,proto3" json:"team_url,omitempty"`
	OrganizationAvatarUrl string   `protobuf:"bytes,7,opt,name=organization_avatar_url,json=organizationAvatarUrl,proto3" json:"organization_avatar_url,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{13}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *User) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *User) GetTeamName() string {
	if m != nil {
		return m.TeamName
	}
	return ""
}

func (m *User) GetTeamUrl() string {
	if m != nil {
		return m.TeamUrl
	}
	return ""
}

func (m *User) GetOrganizationAvatarUrl() string {
	if m != nil {
		return m.OrganizationAvatarUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*ReadUserRequest)(nil), "go.micro.api.platform.ReadUserRequest")
	proto.RegisterType((*ReadUserResponse)(nil), "go.micro.api.platform.ReadUserResponse")
	proto.RegisterType((*CreateServiceRequest)(nil), "go.micro.api.platform.CreateServiceRequest")
	proto.RegisterType((*CreateServiceResponse)(nil), "go.micro.api.platform.CreateServiceResponse")
	proto.RegisterType((*ReadServiceRequest)(nil), "go.micro.api.platform.ReadServiceRequest")
	proto.RegisterType((*ReadServiceResponse)(nil), "go.micro.api.platform.ReadServiceResponse")
	proto.RegisterType((*UpdateServiceRequest)(nil), "go.micro.api.platform.UpdateServiceRequest")
	proto.RegisterType((*UpdateServiceResponse)(nil), "go.micro.api.platform.UpdateServiceResponse")
	proto.RegisterType((*DeleteServiceRequest)(nil), "go.micro.api.platform.DeleteServiceRequest")
	proto.RegisterType((*DeleteServiceResponse)(nil), "go.micro.api.platform.DeleteServiceResponse")
	proto.RegisterType((*ListServicesRequest)(nil), "go.micro.api.platform.ListServicesRequest")
	proto.RegisterType((*ListServicesResponse)(nil), "go.micro.api.platform.ListServicesResponse")
	proto.RegisterType((*Service)(nil), "go.micro.api.platform.Service")
	proto.RegisterMapType((map[string]string)(nil), "go.micro.api.platform.Service.MetadataEntry")
	proto.RegisterType((*User)(nil), "go.micro.api.platform.User")
}

func init() { proto.RegisterFile("proto/api.proto", fileDescriptor_ecf0878b123623e2) }

var fileDescriptor_ecf0878b123623e2 = []byte{
	// 562 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xad, 0x9b, 0xff, 0xe9, 0x57, 0xb5, 0xdf, 0x34, 0xa1, 0x26, 0x15, 0xa8, 0xf2, 0x05, 0x7f,
	0xad, 0x5c, 0xa9, 0x48, 0xa8, 0x2a, 0x57, 0xa8, 0x20, 0x71, 0x01, 0x55, 0x08, 0xca, 0x25, 0x8a,
	0x96, 0x64, 0x1a, 0xad, 0xb0, 0xbd, 0x61, 0x77, 0x13, 0x29, 0x3c, 0x00, 0x6f, 0xc8, 0x4b, 0xf0,
	0x14, 0x68, 0xd7, 0xeb, 0x10, 0x47, 0x76, 0xc9, 0x45, 0xee, 0x76, 0x66, 0xcf, 0x9c, 0x33, 0x33,
	0xf2, 0x1e, 0xc3, 0xc1, 0x54, 0x0a, 0x2d, 0x2e, 0xd8, 0x94, 0x87, 0xf6, 0x84, 0x9d, 0x89, 0x08,
	0x63, 0x3e, 0x92, 0x22, 0xb4, 0xb9, 0x88, 0xe9, 0x3b, 0x21, 0xe3, 0xe0, 0x7f, 0x38, 0xe8, 0x13,
	0x1b, 0x0f, 0x14, 0xc9, 0x3e, 0x7d, 0x9f, 0x91, 0xd2, 0xc1, 0x0d, 0x1c, 0xfe, 0x4d, 0xa9, 0xa9,
	0x48, 0x14, 0xe1, 0x05, 0x54, 0x67, 0x8a, 0xa4, 0xef, 0x9d, 0x7a, 0xcf, 0xf6, 0x2e, 0x4f, 0xc2,
	0x42, 0xb2, 0xd0, 0x96, 0x58, 0x60, 0xd0, 0x83, 0xf6, 0x8d, 0x24, 0xa6, 0xe9, 0x33, 0xc9, 0x39,
	0x1f, 0x91, 0x23, 0xc7, 0x2b, 0x68, 0xa8, 0x34, 0xe3, 0xb8, 0x1e, 0x97, 0x70, 0x65, 0x75, 0x19,
	0x3c, 0x38, 0x86, 0xce, 0x1a, 0x63, 0xda, 0x5b, 0x70, 0x0b, 0x68, 0xfa, 0xdd, 0x9a, 0xd0, 0x27,
	0x38, 0xca, 0xf1, 0xb9, 0x15, 0x5c, 0x43, 0xd3, 0x21, 0x94, 0xef, 0x9d, 0x56, 0x36, 0x60, 0x5c,
	0xe2, 0xcd, 0x36, 0x06, 0xd3, 0xf1, 0x96, 0xb7, 0xb1, 0xc6, 0xe8, 0xb6, 0xd1, 0x83, 0xf6, 0x5b,
	0x8a, 0x68, 0xbb, 0x52, 0x6b, 0x8c, 0x4e, 0xaa, 0x03, 0x47, 0x1f, 0xb8, 0xd2, 0x2e, 0xad, 0xb2,
	0xef, 0xa7, 0x0f, 0xed, 0x7c, 0x7a, 0x0b, 0x0b, 0xfc, 0xed, 0x41, 0xc3, 0x65, 0x11, 0xa1, 0x9a,
	0xb0, 0x38, 0x1d, 0xa3, 0xd5, 0xb7, 0x67, 0xf4, 0xa1, 0x31, 0x27, 0xa9, 0xb8, 0x48, 0xfc, 0x5d,
	0x9b, 0xce, 0x42, 0x7c, 0x00, 0x75, 0x25, 0x66, 0x72, 0x44, 0x7e, 0xc5, 0x5e, 0xb8, 0xc8, 0xb0,
	0xe8, 0xc5, 0x94, 0xfc, 0x6a, 0xca, 0x62, 0xce, 0xf8, 0x1e, 0x9a, 0x31, 0x69, 0x36, 0x66, 0x9a,
	0xf9, 0x35, 0xdb, 0xe1, 0xf9, 0xfd, 0x1d, 0x86, 0x1f, 0x1d, 0xfc, 0x5d, 0xa2, 0xe5, 0xa2, 0xbf,
	0xac, 0xee, 0xbe, 0x86, 0xfd, 0xdc, 0x15, 0x1e, 0x42, 0xe5, 0x1b, 0x2d, 0x5c, 0xcf, 0xe6, 0x88,
	0x6d, 0xa8, 0xcd, 0x59, 0x34, 0x23, 0xd7, 0x70, 0x1a, 0x5c, 0xef, 0x5e, 0x79, 0xc1, 0x2f, 0x0f,
	0xaa, 0xe6, 0x29, 0x15, 0x4e, 0xda, 0x86, 0x1a, 0xc5, 0x8c, 0x47, 0x59, 0x99, 0x0d, 0x4c, 0x36,
	0x12, 0x13, 0x9e, 0xb8, 0x21, 0xd3, 0x00, 0x1f, 0x01, 0xb0, 0x39, 0xd3, 0x4c, 0x0e, 0x67, 0x32,
	0x72, 0x93, 0xb6, 0xd2, 0xcc, 0x40, 0x46, 0x78, 0x02, 0x2d, 0x4d, 0x2c, 0x1e, 0x5a, 0x8d, 0x9a,
	0xbd, 0x6d, 0x9a, 0xc4, 0xad, 0xd1, 0x79, 0x08, 0xf6, 0x6c, 0x2b, 0xeb, 0xe9, 0x4a, 0x4d, 0x6c,
	0xea, 0x5e, 0xc1, 0xb1, 0x90, 0x13, 0x96, 0xf0, 0x1f, 0x4c, 0x73, 0x91, 0x0c, 0x57, 0x34, 0x1a,
	0x16, 0xd9, 0x59, 0xbd, 0x7e, 0x93, 0xe9, 0x5d, 0xfe, 0xac, 0x41, 0xb3, 0xe7, 0x36, 0x88, 0x5f,
	0xa0, 0x99, 0xb9, 0x0c, 0x3e, 0x29, 0xd9, 0xf2, 0x9a, 0x33, 0x75, 0x9f, 0xfe, 0x13, 0xe7, 0xbe,
	0xcc, 0x1d, 0x8c, 0x60, 0x3f, 0xe7, 0x16, 0x78, 0x56, 0x52, 0x5b, 0xe4, 0x52, 0xdd, 0xf3, 0xcd,
	0xc0, 0x4b, 0xb5, 0x3b, 0xd8, 0x5b, 0xb1, 0x0c, 0x7c, 0x7e, 0x4f, 0x9f, 0x6b, 0x4a, 0x2f, 0x36,
	0x81, 0xae, 0x4e, 0x95, 0x7b, 0xf5, 0xa5, 0x53, 0x15, 0xb9, 0x4d, 0xe9, 0x54, 0xc5, 0x46, 0x62,
	0xd5, 0x72, 0x0f, 0xbf, 0x54, 0xad, 0xc8, 0x70, 0x4a, 0xd5, 0x8a, 0xbd, 0x64, 0x07, 0x39, 0xfc,
	0xb7, 0x6a, 0x1b, 0x58, 0xb6, 0x99, 0x02, 0xcb, 0xe9, 0x9e, 0x6d, 0x84, 0xcd, 0xa4, 0xbe, 0xd6,
	0xed, 0x2f, 0xf1, 0xe5, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x42, 0x54, 0xf8, 0x55, 0x25, 0x07,
	0x00, 0x00,
}
